import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en' | 'es' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navbar
    'navbar.login': 'Se connecter',
    'navbar.register': 'Créer un compte',
    'navbar.registerShort': "S'inscrire",
    'navbar.marketplace': 'Marketplace (en pause)',
    'navbar.myMissions': 'Mes Missions',
    'navbar.createMission': 'Créer Mission',
    'navbar.messages': 'Messages',
    'navbar.profile': 'Profil',
    'navbar.dashboard': 'Tableau de bord',
    'navbar.favorites': 'Mes favoris',
    'navbar.logout': 'Déconnexion',
    'navbar.newMission': 'Nouvelle mission',
    'navbar.mission': 'Mission',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'Votre réseau social mode',
    'brand.taglinePart1': 'Votre réseau ',
    'brand.taglinePart2': 'social',
    'brand.taglinePart3': ' mode',

    // Home page
    'home.title': 'Le réseau social qui révolutionne la mode',
    'home.subtitle': 'FashionHub connecte les passionnés de mode du monde entier',
    'home.hero.title': 'Trouvez le prestataire parfait avec l\'IA',
    'home.hero.description': 'Plateforme française d\'appels d\'offres inversés avec intelligence artificielle.',
    'home.hero.platformLaunching': 'Plateforme en lancement',
    'home.hero.earlyUsers': 'Premiers utilisateurs',
    'home.hero.discoverMissions': 'Découvrir les missions',
    'home.hero.postMission': 'Poster une mission',
    'home.reverseAuction.title': 'Enchère inversée',
    'home.reverseAuction.description': 'Au lieu de chercher des prestataires, publiez votre besoin et laissez-les venir à vous avec leurs meilleures offres.',
    'home.reverseAuction.details': 'Ne cherche plus le meilleur prix il vient à toi !',
    'home.reverseAuction.result': 'Résultat : des prix plus compétitifs naturellement',
    'home.directContact.title': 'Contact direct',
    'home.directContact.description': 'Accès immédiat aux experts du réseau et au-delà',
    'home.networkValue.title': 'Valorisez votre réseau',
    'home.networkValue.description': 'Générez des revenus en recommandant les bons contacts',
    'home.startButton': 'Commencer',
    
    // Our approach section
    'home.ourApproach.title': 'Notre approche',
    'home.ourApproach.description': 'Nous améliorons le modèle de mise en relation existant avec deux mécanismes simples mais efficaces',
    
    // Paid connection section  
    'home.paidConnection.title': 'Mise en relation payante',
    'home.paidConnection.description': 'Au lieu de prospecter pendant des semaines, payez quelqu\'un qui a déjà le contact pour vous mettre en relation directement.',
    'home.paidConnection.result': 'Résultat : votre réseau devient rentable, les contacts sont immédiats',
    
    // Why it works section
    'home.whyItWorks.title': 'Pourquoi cette combinaison fonctionne',
    'home.whyItWorks.economical.title': 'Économiquement logique',
    'home.whyItWorks.economical.description': 'La concurrence optimise les prix',
    'home.whyItWorks.efficient.title': 'Efficace pour tous',
    'home.whyItWorks.efficient.description': 'Moins de recherche, plus de résultats',
    'home.whyItWorks.profitable.title': 'Réseau rentable',
    'home.whyItWorks.profitable.description': 'Chacun peut devenir apporteur d\'affaires',
    'home.whyItWorks.immediate.title': 'Contacts immédiats',
    'home.whyItWorks.immediate.description': 'Fini la prospection longue',

    // Footer
    'footer.description': 'La plateforme qui connecte talents et opportunités dans tous les domaines. Trouvez le partenaire idéal pour concrétiser vos projets.',
    'footer.madeWithPassion': 'Fait avec passion',
    'footer.navigation': 'Navigation',
    'footer.discoverMissions': 'Découvrir les missions',
    'footer.findExperts': 'Trouver des experts',
    'footer.publishMission': 'Publier une mission',
    'footer.ourConcept': 'Notre concept',
    'footer.mySpace': 'Mon espace',
    'footer.myDashboard': 'Mon tableau de bord',
    'footer.myProfile': 'Mon profil',
    'footer.support': 'Support',
    'footer.legalNotices': 'Mentions légales',
    'footer.sitemap': 'Plan du site',
    'footer.rightsReserved': '© 2024 FashionHub. Tous droits réservés.',
    'footer.service247': 'Service disponible 24h/7j',
    'footer.globalPlatform': '🌍 Plateforme mondiale',
    'footer.securePayments': '🔒 Paiements sécurisés',

    // Mobile navigation
    'mobile.navigation': 'Navigation',
    'mobile.feed': 'Flux',
    'mobile.providers': 'Prestataires',
    'mobile.services': 'Services',
    'mobile.concept': 'Notre concept',
    'mobile.missions': 'Missions',
    'mobile.mySpace': 'Mon Espace',
    'mobile.myFavorites': 'Mes favoris',
    'mobile.collections': 'Collections',
    'mobile.creators': 'Créateurs',
    'mobile.explore': 'Explorer',
    'mobile.new': 'Nouveau',

    // Home page - FashionHub
    'home.fashionhub.badge': 'Réseau social de la mode',
    'home.fashionhub.title': 'FashionHub',
    'home.fashionhub.subtitle': 'Crée ton dressing virtuel, partage tes looks, inspire la communauté',
    'home.fashionhub.description': 'Organise ta garde-robe, compose des tenues et connecte avec des passionnés de mode.',
    'home.fashionhub.startDressing': 'Commencer mon dressing',
    'home.fashionhub.exploreTrends': 'Explorer les tendances',
    'home.fashionhub.viewFeed': 'Voir le feed',
    
    // Features carousel
    'features.title': 'Pourquoi FashionHub ?',
    'features.subtitle': 'Une plateforme complète pour gérer ton style au quotidien',
    'features.wardrobe.title': 'Dressing Virtuel',
    'features.wardrobe.description': 'Catalogue tous tes vêtements avec photos. Organise par catégorie, couleur, saison.',
    'features.looks.title': 'Création de Looks',
    'features.looks.description': 'Assemble tes articles pour créer des tenues complètes et partage-les.',
    'features.feed.title': 'Feed Inspirant',
    'features.feed.description': 'Découvre des looks tendance et sauvegarde tes tenues favorites.',
    'features.community.title': 'Communauté Mode',
    'features.community.description': 'Connecte avec d\'autres passionnés et partage ta passion pour le style.',
    'features.collections.title': 'Collections Thématiques',
    'features.collections.description': 'Crée des boards pour organiser tes looks par occasion ou style.',
    'features.ai.title': 'Suggestions IA',
    'features.ai.description': 'Découvre de nouvelles façons de porter ce que tu as déjà.',
    'features.carousel.prev': 'Précédent',
    'features.carousel.next': 'Suivant',
    
    // How it works section
    'howItWorks.title': 'Comment ça marche ?',
    'howItWorks.subtitle': 'Trois étapes simples pour révolutionner ta façon de gérer ton style',
    'howItWorks.step1.title': 'Catalogue ton dressing',
    'howItWorks.step1.description': 'Prends en photo tous tes vêtements et accessoires. Ajoute-les à ton dressing virtuel avec leurs caractéristiques.',
    'howItWorks.step2.title': 'Crée tes looks',
    'howItWorks.step2.description': 'Combine tes articles pour créer des tenues. Visualise tes looks et partage tes meilleures créations.',
    'howItWorks.step3.title': 'Inspire et connecte',
    'howItWorks.step3.description': 'Partage avec la communauté, découvre de nouvelles idées et construis ton réseau mode.',
    
    // Final CTA
    'finalCta.title': 'Prêt à révolutionner ton style ?',
    'finalCta.subtitle': 'Rejoins la communauté FashionHub',
    'finalCta.description': 'Des milliers de fashionistas partagent déjà leur passion. À ton tour !',
    'finalCta.startButton': 'Créer mon dressing',
    'finalCta.exploreButton': 'Découvrir',

    // Creators page
    'creators.title': 'Créateurs Mode',
    'creators.subtitle': 'Découvre les fashionistas qui inspirent la communauté',
    'creators.searchPlaceholder': 'Rechercher un créateur...',
    'creators.filterByStyle': 'Style',
    'creators.filterByLocation': 'Localisation',
    'creators.allStyles': 'Tous les styles',
    'creators.allLocations': 'Toutes les villes',
    'creators.style.minimalist': 'Minimaliste',
    'creators.style.streetwear': 'Streetwear',
    'creators.style.classic': 'Classique',
    'creators.style.bohemian': 'Bohème',
    'creators.style.vintage': 'Vintage',
    'creators.style.luxury': 'Luxe',
    'creators.looks': 'looks',
    'creators.followers': 'abonnés',
    'creators.follow': 'Suivre',
    'creators.following': 'Abonné',
    'creators.verified': 'Vérifié',
    'creators.viewProfile': 'Voir le profil',
    
    // Collections page
    'collections.title': 'Mes Collections',
    'collections.subtitle': 'Organise tes looks préférés par thème',
    'collections.myCollections': 'Mes Collections',
    'collections.savedLooks': 'Looks sauvegardés',
    'collections.create': 'Créer une collection',
    'collections.createNew': 'Nouvelle collection',
    'collections.name': 'Nom de la collection',
    'collections.namePlaceholder': 'Ex: Looks d\'été 2024',
    'collections.description': 'Description',
    'collections.descriptionPlaceholder': 'Décris le thème de ta collection...',
    'collections.visibility': 'Visibilité',
    'collections.public': 'Public',
    'collections.private': 'Privé',
    'collections.cancel': 'Annuler',
    'collections.save': 'Créer',
    'collections.empty': 'Aucune collection pour le moment',
    'collections.emptyDescription': 'Crée ta première collection pour commencer à organiser tes looks favoris.',
    'collections.items': 'looks',
    'collections.viewCollection': 'Voir la collection',
    'collections.loginRequired': 'Connexion requise',
    'collections.loginMessage': 'Connecte-toi pour accéder à tes collections',
    'collections.login': 'Se connecter',

    // Concept page
    'concept.badge': 'Le réseau social de la mode et du style',
    'concept.title': 'Votre dressing virtuel,',
    'concept.titlePart2': 'votre communauté mode',
    'concept.subtitle': 'Créez votre garde-robe en ligne, composez des looks stylés,',
    'concept.subtitlePart2': 'et partagez votre passion pour la mode avec une communauté inspirante.',
    'concept.feature.wardrobe': 'Dressing virtuel',
    'concept.feature.wardrobeDesc': 'Organisez votre garde-robe',
    'concept.feature.createLooks': 'Créez des looks',
    'concept.feature.createLooksDesc': 'Mix & match créatif',
    'concept.feature.community': 'Communauté mode',
    'concept.feature.communityDesc': 'Partagez et inspirez',
    'concept.feature.aiAssistant': 'Assistant IA',
    'concept.feature.aiAssistantDesc': 'Suggestions personnalisées',
    'concept.createDressing': 'Créer mon dressing',
    'concept.exploreLooks': 'Explorer les looks',
    'concept.stats.users': 'Utilisateurs actifs',
    'concept.stats.looks': 'Looks partagés',
    'concept.stats.items': 'Articles catalogués',
    'concept.stats.collections': 'Collections créées',
    'concept.whyTitle': 'Pourquoi FashionHub ?',
    'concept.whySubtitle': 'Bien plus qu\'un simple dressing virtuel',
    
    // Profile page
    'profile.notAuthenticated': 'Non authentifié',
    'profile.notAuthenticatedMessage': 'Vous devez vous connecter pour accéder à votre profil.',
    'profile.login': 'Se connecter',
    'profile.myWardrobe': 'Mon Dressing',
    'profile.addItem': 'Ajouter un article',
    'profile.stats.items': 'Articles',
    'profile.stats.looks': 'Looks',
    'profile.stats.followers': 'Abonnés',
    'profile.emptyWardrobe': 'Votre dressing est vide',
    'profile.emptyWardrobeMessage': 'Commencez à ajouter vos vêtements pour créer votre garde-robe virtuelle.',
    
    // Messages page
    'messages.title': 'Messages',
    'messages.subtitle': 'Communiquez avec vos clients et prestataires',
    'messages.loginRequired': 'Connexion requise',
    'messages.loginMessage': 'Connectez-vous pour accéder à vos messages',
    'messages.searchPlaceholder': 'Rechercher une conversation...',
    'messages.noConversations': 'Aucune conversation',
    'messages.startConversation': 'Commencez à discuter avec d\'autres membres',
    'messages.typeMessage': 'Tapez votre message...',
    'messages.send': 'Envoyer',
  },
  en: {
    // Navbar
    'navbar.login': 'Sign In',
    'navbar.register': 'Create Account',
    'navbar.registerShort': 'Sign Up',
    'navbar.marketplace': 'Marketplace (en pause)',
    'navbar.myMissions': 'My Missions',
    'navbar.createMission': 'Create Mission',
    'navbar.messages': 'Messages',
    'navbar.profile': 'Profile',
    'navbar.dashboard': 'Dashboard',
    'navbar.favorites': 'My Favorites',
    'navbar.logout': 'Logout',
    'navbar.newMission': 'New Mission',
    'navbar.mission': 'Mission',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'Your fashion social network',
    'brand.taglinePart1': 'Your fashion ',
    'brand.taglinePart2': 'social',
    'brand.taglinePart3': ' network',

    // Home page
    'home.title': 'The platform that modernizes networking',
    'home.subtitle': 'FashionHub connects fashion enthusiasts worldwide',
    'home.hero.title': 'Find the perfect service provider with AI',
    'home.hero.description': 'French platform for reverse bidding with artificial intelligence.',
    'home.hero.platformLaunching': 'Platform launching',
    'home.hero.earlyUsers': 'Early users',
    'home.hero.discoverMissions': 'Discover missions',
    'home.hero.postMission': 'Post a mission',
    'home.reverseAuction.title': 'Reverse Auction',
    'home.reverseAuction.description': 'Instead of searching for service providers, publish your need and let them come to you with their best offers.',
    'home.reverseAuction.details': 'No more searching for the best price, it comes to you!',
    'home.reverseAuction.result': 'Result: naturally more competitive prices',
    'home.directContact.title': 'Direct Contact',
    'home.directContact.description': 'Immediate access to network experts and beyond',
    'home.networkValue.title': 'Monetize your network',
    'home.networkValue.description': 'Generate revenue by recommending the right contacts',
    'home.startButton': 'Get Started',
    
    // Our approach section
    'home.ourApproach.title': 'Our Approach',
    'home.ourApproach.description': 'We improve the existing networking model with two simple but effective mechanisms',
    
    // Paid connection section
    'home.paidConnection.title': 'Paid Networking',
    'home.paidConnection.description': 'Instead of prospecting for weeks, pay someone who already has the contact to connect you directly.',
    'home.paidConnection.result': 'Result: your network becomes profitable, contacts are immediate',
    
    // Why it works section
    'home.whyItWorks.title': 'Why this combination works',
    'home.whyItWorks.economical.title': 'Economically logical',
    'home.whyItWorks.economical.description': 'Competition optimizes prices',
    'home.whyItWorks.efficient.title': 'Efficient for everyone',
    'home.whyItWorks.efficient.description': 'Less searching, more results',
    'home.whyItWorks.profitable.title': 'Profitable network',
    'home.whyItWorks.profitable.description': 'Anyone can become a business broker',
    'home.whyItWorks.immediate.title': 'Immediate contacts',
    'home.whyItWorks.immediate.description': 'No more long prospecting',

    // Footer
    'footer.description': 'The platform that connects talents and opportunities in all domains. Find the ideal partner to bring your projects to life.',
    'footer.madeWithPassion': 'Made with passion',
    'footer.navigation': 'Navigation',
    'footer.discoverMissions': 'Discover missions',
    'footer.findExperts': 'Find experts',
    'footer.publishMission': 'Publish a mission',
    'footer.ourConcept': 'Our concept',
    'footer.mySpace': 'My Space',
    'footer.myDashboard': 'My dashboard',
    'footer.myProfile': 'My profile',
    'footer.support': 'Support',
    'footer.legalNotices': 'Legal notices',
    'footer.sitemap': 'Sitemap',
    'footer.rightsReserved': '© 2024 FashionHub. All rights reserved.',
    'footer.service247': 'Service available 24/7',
    'footer.globalPlatform': '🌍 Global platform',
    'footer.securePayments': '🔒 Secure payments',

    // Mobile navigation
    'mobile.navigation': 'Navigation',
    'mobile.feed': 'Feed',
    'mobile.providers': 'Providers',
    'mobile.services': 'Services',
    'mobile.concept': 'Our concept',
    'mobile.missions': 'Missions',
    'mobile.mySpace': 'My Space',
    'mobile.myFavorites': 'My favorites',
    'mobile.collections': 'Collections',
    'mobile.creators': 'Creators',
    'mobile.explore': 'Explore',
    'mobile.new': 'New',

    // Home page - FashionHub
    'home.fashionhub.badge': 'Fashion Social Network',
    'home.fashionhub.title': 'FashionHub',
    'home.fashionhub.subtitle': 'Create your virtual wardrobe, share your looks, inspire the community',
    'home.fashionhub.description': 'Organize your wardrobe, compose outfits and connect with fashion enthusiasts.',
    'home.fashionhub.startDressing': 'Start my wardrobe',
    'home.fashionhub.exploreTrends': 'Explore trends',
    'home.fashionhub.viewFeed': 'View feed',
    
    // Features carousel
    'features.title': 'Why FashionHub?',
    'features.subtitle': 'A complete platform to manage your daily style',
    'features.wardrobe.title': 'Virtual Wardrobe',
    'features.wardrobe.description': 'Catalog all your clothes with photos. Organize by category, color, season.',
    'features.looks.title': 'Look Creation',
    'features.looks.description': 'Combine your items to create complete outfits and share them.',
    'features.feed.title': 'Inspiring Feed',
    'features.feed.description': 'Discover trending looks and save your favorite outfits.',
    'features.community.title': 'Fashion Community',
    'features.community.description': 'Connect with other enthusiasts and share your passion for style.',
    'features.collections.title': 'Thematic Collections',
    'features.collections.description': 'Create boards to organize your looks by occasion or style.',
    'features.ai.title': 'AI Suggestions',
    'features.ai.description': 'Discover new ways to wear what you already have.',
    'features.carousel.prev': 'Previous',
    'features.carousel.next': 'Next',
    
    // How it works section
    'howItWorks.title': 'How does it work?',
    'howItWorks.subtitle': 'Three simple steps to revolutionize how you manage your style',
    'howItWorks.step1.title': 'Catalog your wardrobe',
    'howItWorks.step1.description': 'Take photos of all your clothes and accessories. Add them to your virtual wardrobe with their features.',
    'howItWorks.step2.title': 'Create your looks',
    'howItWorks.step2.description': 'Combine your items to create outfits. Visualize your looks and share your best creations.',
    'howItWorks.step3.title': 'Inspire and connect',
    'howItWorks.step3.description': 'Share with the community, discover new ideas and build your fashion network.',
    
    // Final CTA
    'finalCta.title': 'Ready to revolutionize your style?',
    'finalCta.subtitle': 'Join the FashionHub community',
    'finalCta.description': 'Thousands of fashionistas already share their passion. Your turn!',
    'finalCta.startButton': 'Create my wardrobe',
    'finalCta.exploreButton': 'Discover',

    // Creators page
    'creators.title': 'Fashion Creators',
    'creators.subtitle': 'Discover the fashionistas inspiring the community',
    'creators.searchPlaceholder': 'Search for a creator...',
    'creators.filterByStyle': 'Style',
    'creators.filterByLocation': 'Location',
    'creators.allStyles': 'All styles',
    'creators.allLocations': 'All cities',
    'creators.style.minimalist': 'Minimalist',
    'creators.style.streetwear': 'Streetwear',
    'creators.style.classic': 'Classic',
    'creators.style.bohemian': 'Bohemian',
    'creators.style.vintage': 'Vintage',
    'creators.style.luxury': 'Luxury',
    'creators.looks': 'looks',
    'creators.followers': 'followers',
    'creators.follow': 'Follow',
    'creators.following': 'Following',
    'creators.verified': 'Verified',
    'creators.viewProfile': 'View profile',
    
    // Collections page
    'collections.title': 'My Collections',
    'collections.subtitle': 'Organize your favorite looks by theme',
    'collections.myCollections': 'My Collections',
    'collections.savedLooks': 'Saved Looks',
    'collections.create': 'Create a collection',
    'collections.createNew': 'New collection',
    'collections.name': 'Collection name',
    'collections.namePlaceholder': 'E.g: Summer Looks 2024',
    'collections.description': 'Description',
    'collections.descriptionPlaceholder': 'Describe the theme of your collection...',
    'collections.visibility': 'Visibility',
    'collections.public': 'Public',
    'collections.private': 'Private',
    'collections.cancel': 'Cancel',
    'collections.save': 'Create',
    'collections.empty': 'No collections yet',
    'collections.emptyDescription': 'Create your first collection to start organizing your favorite looks.',
    'collections.items': 'looks',
    'collections.viewCollection': 'View collection',
    'collections.loginRequired': 'Login required',
    'collections.loginMessage': 'Sign in to access your collections',
    'collections.login': 'Sign in',

    // Concept page
    'concept.badge': 'The social network of fashion and style',
    'concept.title': 'Your virtual wardrobe,',
    'concept.titlePart2': 'your fashion community',
    'concept.subtitle': 'Create your online wardrobe, compose stylish looks,',
    'concept.subtitlePart2': 'and share your passion for fashion with an inspiring community.',
    'concept.feature.wardrobe': 'Virtual wardrobe',
    'concept.feature.wardrobeDesc': 'Organize your wardrobe',
    'concept.feature.createLooks': 'Create looks',
    'concept.feature.createLooksDesc': 'Creative mix & match',
    'concept.feature.community': 'Fashion community',
    'concept.feature.communityDesc': 'Share and inspire',
    'concept.feature.aiAssistant': 'AI Assistant',
    'concept.feature.aiAssistantDesc': 'Personalized suggestions',
    'concept.createDressing': 'Create my wardrobe',
    'concept.exploreLooks': 'Explore looks',
    'concept.stats.users': 'Active users',
    'concept.stats.looks': 'Looks shared',
    'concept.stats.items': 'Items cataloged',
    'concept.stats.collections': 'Collections created',
    'concept.whyTitle': 'Why FashionHub?',
    'concept.whySubtitle': 'Much more than just a virtual wardrobe',
    
    // Profile page
    'profile.notAuthenticated': 'Not authenticated',
    'profile.notAuthenticatedMessage': 'You must sign in to access your profile.',
    'profile.login': 'Sign in',
    'profile.myWardrobe': 'My Wardrobe',
    'profile.addItem': 'Add item',
    'profile.stats.items': 'Items',
    'profile.stats.looks': 'Looks',
    'profile.stats.followers': 'Followers',
    'profile.emptyWardrobe': 'Your wardrobe is empty',
    'profile.emptyWardrobeMessage': 'Start adding your clothes to create your virtual wardrobe.',
    
    // Messages page
    'messages.title': 'Messages',
    'messages.subtitle': 'Communicate with your clients and providers',
    'messages.loginRequired': 'Login required',
    'messages.loginMessage': 'Sign in to access your messages',
    'messages.searchPlaceholder': 'Search for a conversation...',
    'messages.noConversations': 'No conversations',
    'messages.startConversation': 'Start chatting with other members',
    'messages.typeMessage': 'Type your message...',
    'messages.send': 'Send',
  },
  es: {
    // Navbar
    'navbar.login': 'Iniciar sesión',
    'navbar.register': 'Crear cuenta',
    'navbar.registerShort': 'Registrarse',
    'navbar.marketplace': 'Mercado',
    'navbar.myMissions': 'Mis Misiones',
    'navbar.createMission': 'Crear Misión',
    'navbar.messages': 'Mensajes',
    'navbar.profile': 'Perfil',
    'navbar.dashboard': 'Panel',
    'navbar.favorites': 'Mis favoritos',
    'navbar.logout': 'Cerrar sesión',
    'navbar.newMission': 'Nueva misión',
    'navbar.mission': 'Misión',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'Tu red social de moda',
    'brand.taglinePart1': 'Tu red ',
    'brand.taglinePart2': 'social',
    'brand.taglinePart3': ' de moda',

    // Home page
    'home.title': 'La plataforma que moderniza las conexiones',
    'home.subtitle': 'FashionHub conecta a los amantes de la moda en todo el mundo',
    'home.hero.title': 'Encuentra el proveedor perfecto con IA',
    'home.hero.description': 'Plataforma francesa de licitaciones inversas con inteligencia artificial.',
    'home.hero.platformLaunching': 'Plataforma en lanzamiento',
    'home.hero.earlyUsers': 'Primeros usuarios',
    'home.hero.discoverMissions': 'Descubrir misiones',
    'home.hero.postMission': 'Publicar una misión',
    'home.reverseAuction.title': 'Subasta inversa',
    'home.reverseAuction.description': 'En lugar de buscar proveedores, publica tu necesidad y deja que vengan a ti con sus mejores ofertas.',
    'home.reverseAuction.details': '¡No busques más el mejor precio, viene a ti!',
    'home.reverseAuction.result': 'Resultado: precios naturalmente más competitivos',
    'home.directContact.title': 'Contacto directo',
    'home.directContact.description': 'Acceso inmediato a expertos de la red y más allá',
    'home.networkValue.title': 'Monetiza tu red',
    'home.networkValue.description': 'Genera ingresos recomendando los contactos adecuados',
    'home.startButton': 'Comenzar',
    'home.ourApproach.title': 'Nuestro enfoque',
    'home.ourApproach.description': 'Mejoramos el modelo de conexión existente con dos mecanismos simples pero efectivos',
    'home.paidConnection.title': 'Conexión pagada',
    'home.paidConnection.description': 'En lugar de prospectar durante semanas, paga a alguien que ya tenga el contacto para conectarte directamente.',
    'home.paidConnection.result': 'Resultado: tu red se vuelve rentable, los contactos son inmediatos',
    'home.whyItWorks.title': 'Por qué funciona esta combinación',
    'home.whyItWorks.economical.title': 'Económicamente lógico',
    'home.whyItWorks.economical.description': 'La competencia optimiza los precios',
    'home.whyItWorks.efficient.title': 'Eficiente para todos',
    'home.whyItWorks.efficient.description': 'Menos búsqueda, más resultados',
    'home.whyItWorks.profitable.title': 'Red rentable',
    'home.whyItWorks.profitable.description': 'Cualquiera puede convertirse en intermediario de negocios',
    'home.whyItWorks.immediate.title': 'Contactos inmediatos',
    'home.whyItWorks.immediate.description': 'Se acabó la prospección prolongada',

    // Footer
    'footer.description': 'La plataforma que conecta talentos y oportunidades en todos los dominios. Encuentra el socio ideal para dar vida a tus proyectos.',
    'footer.madeWithPassion': 'Hecho con pasión',
    'footer.navigation': 'Navegación',
    'footer.discoverMissions': 'Descubrir misiones',
    'footer.findExperts': 'Encontrar expertos',
    'footer.publishMission': 'Publicar una misión',
    'footer.ourConcept': 'Nuestro concepto',
    'footer.mySpace': 'Mi Espacio',
    'footer.myDashboard': 'Mi panel',
    'footer.myProfile': 'Mi perfil',
    'footer.support': 'Soporte',
    'footer.legalNotices': 'Avisos legales',
    'footer.sitemap': 'Mapa del sitio',
    'footer.rightsReserved': '© 2024 FashionHub. Todos los derechos reservados.',
    'footer.service247': 'Servicio disponible 24/7',
    'footer.globalPlatform': '🌍 Plataforma global',
    'footer.securePayments': '🔒 Pagos seguros',

    // Mobile navigation
    'mobile.navigation': 'Navegación',
    'mobile.feed': 'Feed',
    'mobile.providers': 'Proveedores',
    'mobile.services': 'Servicios',
    'mobile.concept': 'Nuestro concepto',
    'mobile.missions': 'Misiones',
    'mobile.mySpace': 'Mi Espacio',
    'mobile.myFavorites': 'Mis favoritos',
  },
  ar: {
    // Navbar
    'navbar.login': 'تسجيل الدخول',
    'navbar.register': 'إنشاء حساب',
    'navbar.registerShort': 'التسجيل',
    'navbar.marketplace': 'السوق',
    'navbar.myMissions': 'مهامي',
    'navbar.createMission': 'إنشاء مهمة',
    'navbar.messages': 'الرسائل',
    'navbar.profile': 'الملف الشخصي',
    'navbar.dashboard': 'لوحة التحكم',
    'navbar.favorites': 'المفضلة',
    'navbar.logout': 'تسجيل الخروج',
    'navbar.newMission': 'مهمة جديدة',
    'navbar.mission': 'مهمة',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'شبكتك الاجتماعية للموضة',
    'brand.taglinePart1': 'شبكتك ',
    'brand.taglinePart2': 'الاجتماعية',
    'brand.taglinePart3': ' للموضة',

    // Home page
    'home.title': 'المنصة التي تحدث الاتصالات',
    'home.subtitle': 'Swideal يحول كل تعاون إلى فرصة مربحة للجانبين',
    'home.hero.title': 'ابحث عن مزود الخدمة المثالي بالذكاء الاصطناعي',
    'home.hero.description': 'منصة فرنسية للمناقصات العكسية بالذكاء الاصطناعي.',
    'home.hero.platformLaunching': 'إطلاق المنصة',
    'home.hero.earlyUsers': 'المستخدمون الأوائل',
    'home.hero.discoverMissions': 'اكتشف المهام',
    'home.hero.postMission': 'نشر مهمة',
    'home.reverseAuction.title': 'مزاد عكسي',
    'home.reverseAuction.description': 'بدلاً من البحث عن مزودي الخدمات، انشر احتياجك ودعهم يأتون إليك بأفضل عروضهم.',
    'home.reverseAuction.details': 'لا تبحث عن أفضل سعر، سيأتي إليك!',
    'home.reverseAuction.result': 'النتيجة: أسعار أكثر تنافسية بشكل طبيعي',
    'home.directContact.title': 'اتصال مباشر',
    'home.directContact.description': 'وصول فوري إلى خبراء الشبكة وما بعدها',
    'home.networkValue.title': 'استثمر شبكتك',
    'home.networkValue.description': 'حقق دخلاً من خلال التوصية بجهات الاتصال المناسبة',
    'home.startButton': 'ابدأ',
    'home.ourApproach.title': 'نهجنا',
    'home.ourApproach.description': 'نحسن نموذج الاتصال الحالي بآليتين بسيطتين ولكن فعالتين',
    'home.paidConnection.title': 'اتصال مدفوع',
    'home.paidConnection.description': 'بدلاً من التنقيب لأسابيع، ادفع لشخص لديه جهة الاتصال بالفعل ليوصلك مباشرة.',
    'home.paidConnection.result': 'النتيجة: شبكتك تصبح مربحة، جهات الاتصال فورية',
    'home.whyItWorks.title': 'لماذا يعمل هذا المزيج',
    'home.whyItWorks.economical.title': 'منطقي اقتصادياً',
    'home.whyItWorks.economical.description': 'المنافسة تحسن الأسعار',
    'home.whyItWorks.efficient.title': 'فعال للجميع',
    'home.whyItWorks.efficient.description': 'بحث أقل، نتائج أكثر',
    'home.whyItWorks.profitable.title': 'شبكة مربحة',
    'home.whyItWorks.profitable.description': 'يمكن لأي شخص أن يصبح وسيط أعمال',
    'home.whyItWorks.immediate.title': 'جهات اتصال فورية',
    'home.whyItWorks.immediate.description': 'انتهى التنقيب الطويل',

    // Footer
    'footer.description': 'المنصة التي تربط المواهب والفرص في جميع المجالات. ابحث عن الشريك المثالي لإحياء مشاريعك.',
    'footer.madeWithPassion': 'صُنع بشغف',
    'footer.navigation': 'التنقل',
    'footer.discoverMissions': 'اكتشف المهام',
    'footer.findExperts': 'ابحث عن خبراء',
    'footer.publishMission': 'نشر مهمة',
    'footer.ourConcept': 'مفهومنا',
    'footer.mySpace': 'مساحتي',
    'footer.myDashboard': 'لوحة التحكم',
    'footer.myProfile': 'ملفي الشخصي',
    'footer.support': 'الدعم',
    'footer.legalNotices': 'الإشعارات القانونية',
    'footer.sitemap': 'خريطة الموقع',
    'footer.rightsReserved': '© 2024 Swideal. جميع الحقوق محفوظة.',
    'footer.service247': 'خدمة متاحة 24/7',
    'footer.globalPlatform': '🌍 منصة عالمية',
    'footer.securePayments': '🔒 مدفوعات آمنة',

    // Mobile navigation
    'mobile.navigation': 'التنقل',
    'mobile.feed': 'التغذية',
    'mobile.providers': 'مزودو الخدمات',
    'mobile.services': 'الخدمات',
    'mobile.concept': 'مفهومنا',
    'mobile.missions': 'المهام',
    'mobile.mySpace': 'مساحتي',
    'mobile.myFavorites': 'المفضلة',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}