import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en' | 'es' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Navbar
    'navbar.login': 'Se connecter',
    'navbar.register': 'Créer un compte',
    'navbar.registerShort': "S'inscrire",
    'navbar.marketplace': 'Marketplace (en pause)',
    'navbar.myMissions': 'Mes Missions',
    'navbar.createMission': 'Créer Mission',
    'navbar.messages': 'Messages',
    'navbar.profile': 'Profil',
    'navbar.dashboard': 'Tableau de bord',
    'navbar.favorites': 'Mes favoris',
    'navbar.logout': 'Déconnexion',
    'navbar.newMission': 'Nouvelle mission',
    'navbar.mission': 'Mission',
    'navbar.addClothing': 'Ajouter un vêtement',
    'navbar.settings': 'Paramètres',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'Votre réseau social mode',
    'brand.taglinePart1': 'Votre réseau ',
    'brand.taglinePart2': 'social',
    'brand.taglinePart3': ' mode',

    // Home page
    'home.title': 'Le réseau social qui révolutionne la mode',
    'home.subtitle': 'FashionHub connecte les passionnés de mode du monde entier',
    'home.hero.title': 'Trouvez le prestataire parfait avec l\'IA',
    'home.hero.description': 'Plateforme française d\'appels d\'offres inversés avec intelligence artificielle.',
    'home.hero.platformLaunching': 'Plateforme en lancement',
    'home.hero.earlyUsers': 'Premiers utilisateurs',
    'home.hero.discoverMissions': 'Découvrir les missions',
    'home.hero.postMission': 'Poster une mission',
    'home.reverseAuction.title': 'Enchère inversée',
    'home.reverseAuction.description': 'Au lieu de chercher des prestataires, publiez votre besoin et laissez-les venir à vous avec leurs meilleures offres.',
    'home.reverseAuction.details': 'Ne cherche plus le meilleur prix il vient à toi !',
    'home.reverseAuction.result': 'Résultat : des prix plus compétitifs naturellement',
    'home.directContact.title': 'Contact direct',
    'home.directContact.description': 'Accès immédiat aux experts du réseau et au-delà',
    'home.networkValue.title': 'Valorisez votre réseau',
    'home.networkValue.description': 'Générez des revenus en recommandant les bons contacts',
    'home.startButton': 'Commencer',
    'home.ourApproach.title': 'Notre approche',
    'home.ourApproach.description': 'Nous améliorons le modèle de mise en relation existant avec deux mécanismes simples mais efficaces',
    'home.paidConnection.title': 'Mise en relation payante',
    'home.paidConnection.description': 'Au lieu de prospecter pendant des semaines, payez quelqu\'un qui a déjà le contact pour vous mettre en relation directement.',
    'home.paidConnection.result': 'Résultat : votre réseau devient rentable, les contacts sont immédiats',
    'home.whyItWorks.title': 'Pourquoi cette combinaison fonctionne',
    'home.whyItWorks.economical.title': 'Économiquement logique',
    'home.whyItWorks.economical.description': 'La concurrence optimise les prix',
    'home.whyItWorks.efficient.title': 'Efficace pour tous',
    'home.whyItWorks.efficient.description': 'Moins de recherche, plus de résultats',
    'home.whyItWorks.profitable.title': 'Réseau rentable',
    'home.whyItWorks.profitable.description': 'Chacun peut devenir apporteur d\'affaires',
    'home.whyItWorks.immediate.title': 'Contacts immédiats',
    'home.whyItWorks.immediate.description': 'Fini la prospection longue',

    // Footer
    'footer.description': 'La plateforme qui connecte talents et opportunités dans tous les domaines. Trouvez le partenaire idéal pour concrétiser vos projets.',
    'footer.madeWithPassion': 'Fait avec passion',
    'footer.navigation': 'Navigation',
    'footer.discoverMissions': 'Découvrir les missions',
    'footer.findExperts': 'Trouver des experts',
    'footer.publishMission': 'Publier une mission',
    'footer.ourConcept': 'Notre concept',
    'footer.mySpace': 'Mon espace',
    'footer.myDashboard': 'Mon tableau de bord',
    'footer.myProfile': 'Mon profil',
    'footer.support': 'Support',
    'footer.legalNotices': 'Mentions légales',
    'footer.sitemap': 'Plan du site',
    'footer.rightsReserved': '© 2024 FashionHub. Tous droits réservés.',
    'footer.service247': 'Service disponible 24h/7j',
    'footer.globalPlatform': '🌍 Plateforme mondiale',
    'footer.securePayments': '🔒 Paiements sécurisés',

    // Mobile navigation
    'mobile.navigation': 'Navigation',
    'mobile.feed': 'Flux',
    'mobile.providers': 'Prestataires',
    'mobile.services': 'Services',
    'mobile.concept': 'Notre concept',
    'mobile.missions': 'Missions',
    'mobile.mySpace': 'Mon Espace',
    'mobile.myFavorites': 'Mes favoris',
    'mobile.collections': 'Collections',
    'mobile.creators': 'Créateurs',
    'mobile.explore': 'Explorer',
    'mobile.new': 'Nouveau',

    // Home page - FashionHub
    'home.fashionhub.badge': 'Réseau social de la mode',
    'home.fashionhub.title': 'FashionHub',
    'home.fashionhub.subtitle': 'Crée ton dressing virtuel, partage tes looks, inspire la communauté',
    'home.fashionhub.description': 'Organise ta garde-robe, compose des tenues et connecte avec des passionnés de mode.',
    'home.fashionhub.startDressing': 'Commencer mon dressing',
    'home.fashionhub.exploreTrends': 'Explorer les tendances',
    'home.fashionhub.viewFeed': 'Voir le feed',
    
    // Features page
    'features.badge': 'Fonctionnalités Complètes',
    'features.title': 'Découvrez tout ce que FashionHub peut faire pour votre style',
    'features.subtitle': 'Une plateforme complète avec des fonctionnalités avancées pour organiser votre garde-robe, créer des looks stylés et partager votre passion pour la mode.',
    'features.startNow': 'Commencer maintenant',
    'features.fashionistas': 'Fashionistas actifs',
    'features.looksShared': 'Looks partagés',
    'features.satisfaction': 'Taux de satisfaction',
    'features.itemsCataloged': 'Articles catalogués',
    'features.wardrobe.title': 'Dressing Virtuel',
    'features.wardrobe.description': 'Catalogue tous tes vêtements avec photos. Organise par catégorie, couleur, saison.',
    'features.looks.title': 'Création de Looks',
    'features.looks.description': 'Assemble tes articles pour créer des tenues complètes et partage-les.',
    'features.feed.title': 'Feed Inspirant',
    'features.feed.description': 'Découvre des looks tendance et sauvegarde tes tenues favorites.',
    'features.community.title': 'Communauté Mode',
    'features.community.description': 'Connecte avec d\'autres passionnés et partage ta passion pour le style.',
    'features.collections.title': 'Collections Thématiques',
    'features.collections.description': 'Crée des boards pour organiser tes looks par occasion ou style.',
    'features.ai.title': 'Suggestions IA',
    'features.ai.description': 'Découvre de nouvelles façons de porter ce que tu as déjà.',
    'features.carousel.prev': 'Précédent',
    'features.carousel.next': 'Suivant',
    
    // How it works section
    'howItWorks.title': 'Comment ça marche ?',
    'howItWorks.subtitle': 'Trois étapes simples pour révolutionner ta façon de gérer ton style',
    'howItWorks.step1.title': 'Catalogue ton dressing',
    'howItWorks.step1.description': 'Prends en photo tous tes vêtements et accessoires. Ajoute-les à ton dressing virtuel avec leurs caractéristiques.',
    'howItWorks.step2.title': 'Crée tes looks',
    'howItWorks.step2.description': 'Combine tes articles pour créer des tenues. Visualise tes looks et partage tes meilleures créations.',
    'howItWorks.step3.title': 'Inspire et connecte',
    'howItWorks.step3.description': 'Partage avec la communauté, découvre de nouvelles idées et construis ton réseau mode.',
    
    // Final CTA
    'finalCta.title': 'Prêt à révolutionner ton style ?',
    'finalCta.subtitle': 'Rejoins la communauté FashionHub',
    'finalCta.description': 'Des milliers de fashionistas partagent déjà leur passion. À ton tour !',
    'finalCta.startButton': 'Créer mon dressing',
    'finalCta.exploreButton': 'Découvrir',

    // Creators page
    'creators.title': 'Créateurs Mode',
    'creators.subtitle': 'Découvre les fashionistas qui inspirent la communauté',
    'creators.searchPlaceholder': 'Rechercher un créateur...',
    'creators.searchPlaceholderFull': 'Rechercher un créateur ou un style...',
    'creators.filterByStyle': 'Style',
    'creators.filterByLocation': 'Localisation',
    'creators.allStyles': 'Tous les styles',
    'creators.allLocations': 'Toutes les villes',
    'creators.style.minimalist': 'Minimaliste',
    'creators.style.streetwear': 'Streetwear',
    'creators.style.classic': 'Classique',
    'creators.style.bohemian': 'Bohème',
    'creators.style.vintage': 'Vintage',
    'creators.style.luxury': 'Luxe',
    'creators.looks': 'looks',
    'creators.followers': 'abonnés',
    'creators.follow': 'Suivre',
    'creators.following': 'Abonné',
    'creators.verified': 'Vérifié',
    'creators.viewProfile': 'Voir le profil',
    'creators.filters': 'Filtres',
    'creators.filters.title': 'Filtres de recherche',
    'creators.filters.close': 'Fermer',
    'creators.filters.clear': 'Effacer',
    'creators.filters.styleVestimentaire': 'Style vestimentaire',
    'creators.filters.location': 'Localisation',
    'creators.filters.locationPlaceholder': 'Paris, Lyon, Marseille...',
    'creators.filters.popularity': 'Popularité',
    'creators.filters.activity': 'Activité',
    'creators.filters.allCreators': 'Tous les créateurs',
    'creators.filters.rising': '🔥 En croissance (1k-5k)',
    'creators.filters.established': '⭐ Établis (5k-10k)',
    'creators.filters.popular': '👑 Populaires (10k+)',
    'creators.filters.verifiedOnly': '✓ Vérifiés uniquement',
    'creators.filters.allActivities': 'Toutes activités',
    'creators.filters.veryActive': 'Très actifs (50+ looks)',
    'creators.filters.moderate': 'Modérés (10-50 looks)',
    'creators.filters.newCreators': 'Nouveaux créateurs',
    'creators.filters.results': 'résultats',
    'creators.filters.trending': 'tendance',
    'creators.filters.verified': 'vérifiés',
    'creators.filters.reset': 'Réinitialiser',
    'creators.filters.apply': 'Appliquer',
    'creators.creatorsCount': 'créateur',
    'creators.creatorsCountPlural': 'créateurs',
    'creators.noCreatorsFound': 'Aucun créateur trouvé',
    'creators.adjustFilters': 'Essayez d\'ajuster vos filtres',
    'creators.discoverFashionistas': 'Découvre les fashionistas',
    'creators.followFashionistas': 'Suis les passionnés de mode, inspire-toi de leurs looks et construis ta communauté style',
    
    // Collections page
    'collections.title': 'Mes Collections',
    'collections.subtitle': 'Organise tes looks préférés par thème',
    'collections.myCollections': 'Mes Collections',
    'collections.savedLooks': 'Looks sauvegardés',
    'collections.create': 'Créer une collection',
    'collections.createNew': 'Nouvelle collection',
    'collections.name': 'Nom de la collection',
    'collections.namePlaceholder': 'Ex: Looks d\'été 2024',
    'collections.description': 'Description',
    'collections.descriptionPlaceholder': 'Décris le thème de ta collection...',
    'collections.visibility': 'Visibilité',
    'collections.public': 'Public',
    'collections.private': 'Privé',
    'collections.cancel': 'Annuler',
    'collections.save': 'Créer',
    'collections.empty': 'Aucune collection pour le moment',
    'collections.emptyDescription': 'Crée ta première collection pour commencer à organiser tes looks favoris.',
    'collections.items': 'looks',
    'collections.viewCollection': 'Voir la collection',
    'collections.loginRequired': 'Connexion requise',
    'collections.loginMessage': 'Connecte-toi pour accéder à tes collections',
    'collections.login': 'Se connecter',
    'collections.newCollection': 'Nouvelle Collection',
    'collections.createNewCollection': 'Créer une nouvelle collection',
    'collections.organizeYourFavorites': 'Organisez vos looks favoris dans des collections thématiques',
    'collections.collectionTitle': 'Titre de la collection',
    'collections.collectionTitlePlaceholder': 'Ex: Looks d\'été, Style minimaliste...',
    'collections.collectionDescription': 'Description',
    'collections.collectionDescriptionPlaceholder': 'Décrivez votre collection...',
    'collections.makePublic': 'Rendre cette collection publique',
    'collections.creating': 'Création...',
    'collections.createCollection': 'Créer la collection',
    'collections.editCollection': 'Modifier la collection',
    'collections.editCollectionInfo': 'Modifiez les informations de votre collection',
    'collections.updating': 'Modification...',
    'collections.saveChanges': 'Enregistrer les modifications',
    'collections.noCollections': 'Vous n\'avez pas encore de collections',
    'collections.createFirstCollection': 'Créer ma première collection',
    'collections.view': 'Voir',
    'collections.edit': 'Modifier',
    'collections.delete': 'Supprimer',
    'collections.noSavedLooks': 'Aucun look sauvegardé',
    'collections.exploreFeedToSave': 'Explorez le feed et sauvegardez vos looks préférés',
    'collections.exploreFeed': 'Explorer le feed',
    'collections.count': 'looks',
    'collections.by': 'par',

    // Concept page
    'concept.badge': 'Le réseau social de la mode et du style',
    'concept.title': 'Votre dressing virtuel,',
    'concept.titlePart2': 'votre communauté mode',
    'concept.subtitle': 'Créez votre garde-robe en ligne, composez des looks stylés,',
    'concept.subtitlePart2': 'et partagez votre passion pour la mode avec une communauté inspirante.',
    'concept.feature.wardrobe': 'Dressing virtuel',
    'concept.feature.wardrobeDesc': 'Organisez votre garde-robe',
    'concept.feature.createLooks': 'Créez des looks',
    'concept.feature.createLooksDesc': 'Mix & match créatif',
    'concept.feature.community': 'Communauté mode',
    'concept.feature.communityDesc': 'Partagez et inspirez',
    'concept.feature.aiAssistant': 'Assistant IA',
    'concept.feature.aiAssistantDesc': 'Suggestions personnalisées',
    'concept.createDressing': 'Créer mon dressing',
    'concept.exploreLooks': 'Explorer les looks',
    'concept.stats.users': 'Utilisateurs actifs',
    'concept.stats.looks': 'Looks partagés',
    'concept.stats.items': 'Articles catalogués',
    'concept.stats.collections': 'Collections créées',
    'concept.whyTitle': 'Pourquoi FashionHub ?',
    'concept.whySubtitle': 'Bien plus qu\'un simple dressing virtuel',
    'concept.whatYouWillLove': 'Ce que vous allez adorer :',
    'concept.organizeWardrobe': 'Organisez votre garde-robe',
    'concept.organizeWardrobeDesc': 'Cataloguez vos vêtements',
    'concept.createOutfits': 'Créez des tenues',
    'concept.createOutfitsDesc': 'Mix & match créatif',
    'concept.sharePassion': 'Partagez votre passion',
    'concept.sharePassionDesc': 'Communauté inspirante',
    'concept.aiSuggestions': 'Suggestions IA',
    'concept.aiSuggestionsDesc': 'Recommandations personnalisées',
    'concept.organizeYourInspiration': 'Organisez votre inspiration',
    'concept.createThematicCollections': 'Créez des collections thématiques et organisez vos looks préférés',
    'concept.howItWorks': 'Comment ça marche ?',
    'concept.fourSteps': '4 étapes pour devenir une fashionista connectée',
    'concept.completeFeatures': 'Fonctionnalités complètes',
    'concept.everythingForYourStyle': 'Tout ce dont vous avez besoin pour gérer votre style',
    'concept.theyLove': 'Ils adorent FashionHub',
    'concept.communityTestimonials': 'Témoignages de notre communauté',
    'concept.faq': 'Questions fréquentes',
    'concept.faqSubtitle': 'Tout ce que vous devez savoir',
    'concept.readyToRevolutionize': 'Prêt à révolutionner votre style ?',
    'concept.joinCommunity': 'Rejoignez des milliers de fashionistas qui transforment leur passion mode en partage créatif',
    'concept.startFree': 'Commencer gratuitement',
    
    // Profile page
    'profile.notAuthenticated': 'Non authentifié',
    'profile.notAuthenticatedMessage': 'Vous devez vous connecter pour accéder à votre profil.',
    'profile.login': 'Se connecter',
    'profile.myWardrobe': 'Mon Dressing',
    'profile.addItem': 'Ajouter un article',
    'profile.stats.items': 'Articles',
    'profile.stats.looks': 'Looks',
    'profile.stats.followers': 'Abonnés',
    'profile.emptyWardrobe': 'Votre dressing est vide',
    'profile.emptyWardrobeMessage': 'Commencez à ajouter vos vêtements pour créer votre garde-robe virtuelle.',
    
    // Dashboard page
    'dashboard.passionateAbout': 'Passionné(e) de mode et de style',
    'dashboard.viewProfile': 'Voir mon profil',
    'dashboard.itemsInWardrobe': 'Articles dans le dressing',
    'dashboard.yourVirtualWardrobe': 'Ton dressing virtuel',
    'dashboard.likesReceived': 'J\'aime reçus',
    'dashboard.onAllLooks': 'Sur tous tes looks',
    'dashboard.sharedLooks': 'Looks partagés',
    'dashboard.visibleByCommunity': 'Visibles par la communauté',
    'dashboard.subscribers': 'Abonnés',
    'dashboard.fashionistasFollowing': 'Fashionistas qui te suivent',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.myWardrobe': 'Mon dressing',
    'dashboard.statistics': 'Statistiques',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.addArticle': 'Ajouter un article',
    'dashboard.exploreFeed': 'Explorer le feed',
    'dashboard.viewPublicProfile': 'Voir mon profil public',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.noArticles': 'Aucun article pour le moment',
    'dashboard.articles': 'articles',
    'dashboard.addClothingToWardrobe': 'Ajouter un vêtement à ton dressing',
    'dashboard.wardrobeEmpty': 'Ton dressing est vide',
    'dashboard.startAddingClothes': 'Commence à ajouter tes vêtements pour créer ton dressing virtuel',
    'dashboard.addFirstArticle': 'Ajouter mon premier article',
    'dashboard.detailedStats': 'Statistiques détaillées',
    'dashboard.looksPerformance': 'Performance de tes looks',
    'dashboard.totalViews': 'Vues totales',
    'dashboard.likes': 'J\'aime',
    'dashboard.comments': 'Commentaires',
    'dashboard.saves': 'Sauvegardes',
    'dashboard.wardrobeInNumbers': 'Ton dressing en chiffres',
    'dashboard.totalArticles': 'Total d\'articles',
    'dashboard.looksCreated': 'Looks créés',
    'dashboard.publicationRate': 'Taux de publication',
    
    // Profile page - additional texts
    'profile.tabs.wardrobe': 'Garde-robe',
    'profile.tabs.looks': 'Looks',
    'profile.tabs.favorites': 'Favoris',
    'profile.tabs.clothes': 'Vêtements',
    'profile.editProfile': 'Modifier le profil',
    'profile.editProfile.title': 'Modifier mon profil',
    'profile.editProfile.subtitle': 'Personnalisez votre profil FashionHub',
    'profile.editProfile.name': 'Nom',
    'profile.editProfile.username': 'Nom d\'utilisateur',
    'profile.editProfile.bio': 'Bio',
    'profile.editProfile.bioPlaceholder': 'Parlez-nous de votre style...',
    'profile.editProfile.avatarUrl': 'URL de l\'avatar',
    'profile.editProfile.styleTags': 'Tags de style',
    'profile.editProfile.addTag': 'Ajouter un tag (ex: streetwear)',
    'profile.editProfile.pressEnter': 'Appuyez sur Entrée pour ajouter un tag',
    'profile.editProfile.cancel': 'Annuler',
    'profile.editProfile.save': 'Enregistrer',
    'profile.editProfile.saving': 'Enregistrement...',
    'profile.addItem.title': 'Ajouter un vêtement',
    'profile.addItem.subtitle': 'Ajoutez un nouveau vêtement à votre garde-robe virtuelle',
    'profile.addItem.itemName': 'Nom du vêtement',
    'profile.addItem.itemNamePlaceholder': 'Ex: T-shirt blanc basique',
    'profile.addItem.category': 'Catégorie',
    'profile.addItem.categoryPlaceholder': 'Sélectionner une catégorie',
    'profile.addItem.categoryTop': 'Haut',
    'profile.addItem.categoryBottom': 'Bas',
    'profile.addItem.categoryShoes': 'Chaussures',
    'profile.addItem.categoryDress': 'Robe',
    'profile.addItem.categoryOuterwear': 'Veste/Manteau',
    'profile.addItem.categoryAccessory': 'Accessoire',
    'profile.addItem.categoryBag': 'Sac',
    'profile.addItem.brand': 'Marque',
    'profile.addItem.brandPlaceholder': 'Ex: Zara, H&M...',
    'profile.addItem.size': 'Taille',
    'profile.addItem.sizePlaceholder': 'Ex: M, 38...',
    'profile.addItem.color': 'Couleur',
    'profile.addItem.colorPlaceholder': 'Ex: blanc, noir, bleu marine...',
    'profile.addItem.season': 'Saison',
    'profile.addItem.seasonAll': 'Toute l\'année',
    'profile.addItem.seasonSpring': 'Printemps',
    'profile.addItem.seasonSummer': 'Été',
    'profile.addItem.seasonFall': 'Automne',
    'profile.addItem.seasonWinter': 'Hiver',
    'profile.addItem.occasion': 'Occasion',
    'profile.addItem.occasionCasual': 'Décontracté',
    'profile.addItem.occasionFormal': 'Formel',
    'profile.addItem.occasionSport': 'Sport',
    'profile.addItem.occasionParty': 'Soirée',
    'profile.addItem.description': 'Description',
    'profile.addItem.descriptionPlaceholder': 'Décrivez votre vêtement...',
    'profile.addItem.cancel': 'Annuler',
    'profile.addItem.add': 'Ajouter',
    'profile.addItem.adding': 'Ajout...',
    'profile.wardrobe.addClothing': 'Ajouter un vêtement',
    'profile.wardrobe.addFirstItem': 'Ajouter mon premier vêtement',
    'profile.looks.createFirstLook': 'Créer mon premier look',
    'profile.looks.noLooks': 'Aucun look créé',
    'profile.looks.noLooksMessage': 'Créez votre premier look en combinant vos vêtements',
    'profile.favorites.noFavorites': 'Aucun favori',
    'profile.favorites.noFavoritesMessage': 'Likez des looks pour les retrouver ici',
    'profile.stats.posts': 'Posts',
    'profile.stats.following': 'Suivis',
    'profile.verified': 'Vérifié',
    
    // Feed page
    'feed.title': 'Feed Mode',
    'feed.searchPlaceholder': 'Rechercher un style, une couleur...',
    'feed.addLook': 'Ajouter un look',
    'feed.allLooks': 'Tous les looks',
    'feed.trending': 'Tendances',
    'feed.following': 'Abonnements',
    'feed.noLooks': 'Aucun look pour le moment',
    'feed.noLooksMessage': 'Sois le premier à partager ton style !',
    'feed.createFirstLook': 'Créer mon premier look',
    
    // Explore page
    'explore.title': 'Explorer',
    'explore.subtitle': 'Découvrez les tendances, styles et fashionistas du moment',
    'explore.searchPlaceholder': 'Rechercher des looks, utilisateurs, marques...',
    'explore.trends': 'Tendances',
    'explore.people': 'Personnes',
    'explore.hashtags': 'Hashtags',

    // Settings page
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Gérez vos préférences et paramètres de compte',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Confidentialité',
    'settings.appearance': 'Apparence',
    'settings.save': 'Sauvegarder',
    'settings.loginRequired': 'Connexion requise',
    'settings.loginMessage': 'Connectez-vous pour accéder aux paramètres',

    // Legal page
    'legal.title': 'Mentions Légales & Politique de Confidentialité',
    'legal.lastUpdate': 'Dernière mise à jour',
    'legal.editor.title': 'Éditeur du site',
    'legal.editor.company': 'Nom de l\'entreprise',
    'legal.editor.address': 'Adresse',
    'legal.editor.email': 'Email',
    'legal.editor.director': 'Directeur de la publication',
    'legal.hosting.title': 'Hébergement',
    'legal.hosting.host': 'Hébergeur',
    'legal.hosting.address': 'Adresse',
    'legal.data.title': 'Collecte des données personnelles',
    'legal.data.intro': 'Dans le cadre de l\'utilisation de notre plateforme, nous collectons les données suivantes :',
    'legal.data.name': 'Nom et prénom',
    'legal.data.email': 'Adresse email',
    'legal.data.photos': 'Photos de vêtements et looks que vous partagez',
    'legal.data.profile': 'Informations de profil (bio, tags de style)',
    'legal.data.navigation': 'Données de navigation (cookies techniques)',
    'legal.usage.title': 'Utilisation des données',
    'legal.usage.intro': 'Vos données personnelles sont utilisées pour :',
    'legal.usage.account': 'Créer et gérer votre compte utilisateur',
    'legal.usage.wardrobe': 'Organiser votre dressing virtuel',
    'legal.usage.share': 'Partager vos looks avec la communauté',
    'legal.usage.recommendations': 'Personnaliser vos recommandations de style',
    'legal.usage.improve': 'Améliorer nos services',
    'legal.usage.notifications': 'Vous envoyer des notifications importantes',
    'legal.rights.title': 'Vos droits',
    'legal.rights.intro': 'Conformément au RGPD, vous disposez des droits suivants :',
    'legal.rights.access': 'Droit d\'accès à vos données',
    'legal.rights.rectification': 'Droit de rectification',
    'legal.rights.erasure': 'Droit à l\'effacement',
    'legal.rights.portability': 'Droit à la portabilité des données',
    'legal.rights.objection': 'Droit d\'opposition',
    'legal.rights.contact': 'Pour exercer ces droits, contactez-nous à l\'adresse :',
    'legal.terms.title': 'Conditions Générales d\'Utilisation',
    'legal.terms.article1.title': 'Article 1 - Objet',
    'legal.terms.article1.content': 'FashionHub est un réseau social dédié à la mode et au style personnel. La plateforme permet aux utilisateurs de créer leur dressing virtuel, composer des looks et partager leur passion pour la mode.',
    'legal.terms.article2.title': 'Article 2 - Services',
    'legal.terms.article2.intro': 'Nous proposons les services suivants :',
    'legal.terms.article2.service1': 'Création et gestion d\'un dressing virtuel',
    'legal.terms.article2.service2': 'Création et partage de looks',
    'legal.terms.article2.service3': 'Interaction avec la communauté (likes, commentaires, abonnements)',
    'legal.terms.article2.service4': 'Collections thématiques personnalisées',
    'legal.terms.article2.service5': 'Suggestions de style par intelligence artificielle',
    'legal.terms.article3.title': 'Article 3 - Responsabilités',
    'legal.terms.article3.content': 'FashionHub agit en tant que plateforme d\'hébergement de contenu. Les utilisateurs sont seuls responsables des contenus qu\'ils publient et doivent respecter les droits d\'auteur et la propriété intellectuelle.',
    'legal.terms.article4.title': 'Article 4 - Tarifs',
    'legal.terms.article4.content': 'L\'inscription et l\'utilisation de FashionHub sont entièrement gratuites. Aucun frais caché n\'est appliqué aux utilisateurs.',
    'legal.terms.article5.title': 'Article 5 - Contenu',
    'legal.terms.article5.content': 'En publiant du contenu sur FashionHub, vous accordez à la plateforme une licence non-exclusive pour afficher, distribuer et promouvoir votre contenu. Vous conservez tous vos droits de propriété intellectuelle.',
    'legal.terms.article6.title': 'Article 6 - Modération',
    'legal.terms.article6.content': 'FashionHub se réserve le droit de modérer et supprimer tout contenu inapproprié, offensant ou contraire à nos conditions d\'utilisation.',
    'legal.cookies.title': 'Cookies',
    'legal.cookies.content': 'Notre site utilise uniquement des cookies techniques nécessaires au fonctionnement de la plateforme (authentification, préférences utilisateur). Aucun cookie publicitaire ou de tracking n\'est utilisé.',
    'legal.ip.title': 'Propriété Intellectuelle',
    'legal.ip.content': 'Le design, le logo et tous les éléments graphiques de FashionHub sont protégés par les droits d\'auteur. Toute reproduction sans autorisation est interdite.',
    'legal.contact.title': 'Contact',
    'legal.contact.content': 'Pour toute question concernant nos mentions légales ou notre politique de confidentialité, contactez-nous à l\'adresse :',
    
    // Messages page
    'messages.title': 'Messages',
    'messages.subtitle': 'Communiquez avec vos clients et prestataires',
    'messages.loginRequired': 'Connexion requise',
    'messages.loginMessage': 'Connectez-vous pour accéder à vos messages',
    'messages.searchPlaceholder': 'Rechercher une conversation...',
    'messages.noConversations': 'Aucune conversation',
    'messages.startConversation': 'Commencez à discuter avec d\'autres membres',
    'messages.typeMessage': 'Tapez votre message...',
    'messages.send': 'Envoyer',
  },
  en: {
    // Navbar
    'navbar.login': 'Sign In',
    'navbar.register': 'Create Account',
    'navbar.registerShort': 'Sign Up',
    'navbar.marketplace': 'Marketplace (paused)',
    'navbar.myMissions': 'My Missions',
    'navbar.createMission': 'Create Mission',
    'navbar.messages': 'Messages',
    'navbar.profile': 'Profile',
    'navbar.dashboard': 'Dashboard',
    'navbar.favorites': 'My Favorites',
    'navbar.logout': 'Logout',
    'navbar.newMission': 'New Mission',
    'navbar.mission': 'Mission',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'Your fashion social network',
    'brand.taglinePart1': 'Your fashion ',
    'brand.taglinePart2': 'social',
    'brand.taglinePart3': ' network',

    // Home page
    'home.title': 'The social network revolutionizing fashion',
    'home.subtitle': 'FashionHub connects fashion enthusiasts worldwide',
    'home.hero.title': 'Find the perfect service provider with AI',
    'home.hero.description': 'French platform for reverse bidding with artificial intelligence.',
    'home.hero.platformLaunching': 'Platform launching',
    'home.hero.earlyUsers': 'Early users',
    'home.hero.discoverMissions': 'Discover missions',
    'home.hero.postMission': 'Post a mission',
    'home.reverseAuction.title': 'Reverse Auction',
    'home.reverseAuction.description': 'Instead of searching for service providers, publish your need and let them come to you with their best offers.',
    'home.reverseAuction.details': 'No more searching for the best price, it comes to you!',
    'home.reverseAuction.result': 'Result: naturally more competitive prices',
    'home.directContact.title': 'Direct Contact',
    'home.directContact.description': 'Immediate access to network experts and beyond',
    'home.networkValue.title': 'Monetize your network',
    'home.networkValue.description': 'Generate revenue by recommending the right contacts',
    'home.startButton': 'Get Started',
    'home.ourApproach.title': 'Our Approach',
    'home.ourApproach.description': 'We improve the existing networking model with two simple but effective mechanisms',
    'home.paidConnection.title': 'Paid Networking',
    'home.paidConnection.description': 'Instead of prospecting for weeks, pay someone who already has the contact to connect you directly.',
    'home.paidConnection.result': 'Result: your network becomes profitable, contacts are immediate',
    'home.whyItWorks.title': 'Why this combination works',
    'home.whyItWorks.economical.title': 'Economically logical',
    'home.whyItWorks.economical.description': 'Competition optimizes prices',
    'home.whyItWorks.efficient.title': 'Efficient for everyone',
    'home.whyItWorks.efficient.description': 'Less searching, more results',
    'home.whyItWorks.profitable.title': 'Profitable network',
    'home.whyItWorks.profitable.description': 'Anyone can become a business broker',
    'home.whyItWorks.immediate.title': 'Immediate contacts',
    'home.whyItWorks.immediate.description': 'No more long prospecting',

    // Footer
    'footer.description': 'The platform that connects talents and opportunities in all domains. Find the ideal partner to bring your projects to life.',
    'footer.madeWithPassion': 'Made with passion',
    'footer.navigation': 'Navigation',
    'footer.discoverMissions': 'Discover missions',
    'footer.findExperts': 'Find experts',
    'footer.publishMission': 'Publish a mission',
    'footer.ourConcept': 'Our concept',
    'footer.mySpace': 'My Space',
    'footer.myDashboard': 'My dashboard',
    'footer.myProfile': 'My profile',
    'footer.support': 'Support',
    'footer.legalNotices': 'Legal notices',
    'footer.sitemap': 'Sitemap',
    'footer.rightsReserved': '© 2024 FashionHub. All rights reserved.',
    'footer.service247': 'Service available 24/7',
    'footer.globalPlatform': '🌍 Global platform',
    'footer.securePayments': '🔒 Secure payments',

    // Mobile navigation
    'mobile.navigation': 'Navigation',
    'mobile.feed': 'Feed',
    'mobile.providers': 'Providers',
    'mobile.services': 'Services',
    'mobile.concept': 'Our concept',
    'mobile.missions': 'Missions',
    'mobile.mySpace': 'My Space',
    'mobile.myFavorites': 'My favorites',
    'mobile.collections': 'Collections',
    'mobile.creators': 'Creators',
    'mobile.explore': 'Explore',
    'mobile.new': 'New',

    // Home page - FashionHub
    'home.fashionhub.badge': 'Fashion Social Network',
    'home.fashionhub.title': 'FashionHub',
    'home.fashionhub.subtitle': 'Create your virtual wardrobe, share your looks, inspire the community',
    'home.fashionhub.description': 'Organize your wardrobe, compose outfits and connect with fashion enthusiasts.',
    'home.fashionhub.startDressing': 'Start my wardrobe',
    'home.fashionhub.exploreTrends': 'Explore trends',
    'home.fashionhub.viewFeed': 'View feed',
    
    // Features page
    'features.badge': 'Complete Features',
    'features.title': 'Discover everything FashionHub can do for your style',
    'features.subtitle': 'A complete platform with advanced features to organize your wardrobe, create stylish looks and share your passion for fashion.',
    'features.startNow': 'Start now',
    'features.fashionistas': 'Active Fashionistas',
    'features.looksShared': 'Looks shared',
    'features.satisfaction': 'Satisfaction rate',
    'features.itemsCataloged': 'Items cataloged',
    'features.wardrobe.title': 'Virtual Wardrobe',
    'features.wardrobe.description': 'Catalog all your clothes with photos. Organize by category, color, season.',
    'features.looks.title': 'Look Creation',
    'features.looks.description': 'Combine your items to create complete outfits and share them.',
    'features.feed.title': 'Inspiring Feed',
    'features.feed.description': 'Discover trending looks and save your favorite outfits.',
    'features.community.title': 'Fashion Community',
    'features.community.description': 'Connect with other enthusiasts and share your passion for style.',
    'features.collections.title': 'Thematic Collections',
    'features.collections.description': 'Create boards to organize your looks by occasion or style.',
    'features.ai.title': 'AI Suggestions',
    'features.ai.description': 'Discover new ways to wear what you already have.',
    'features.carousel.prev': 'Previous',
    'features.carousel.next': 'Next',
    
    // How it works section
    'howItWorks.title': 'How does it work?',
    'howItWorks.subtitle': 'Three simple steps to revolutionize how you manage your style',
    'howItWorks.step1.title': 'Catalog your wardrobe',
    'howItWorks.step1.description': 'Take photos of all your clothes and accessories. Add them to your virtual wardrobe with their features.',
    'howItWorks.step2.title': 'Create your looks',
    'howItWorks.step2.description': 'Combine your items to create outfits. Visualize your looks and share your best creations.',
    'howItWorks.step3.title': 'Inspire and connect',
    'howItWorks.step3.description': 'Share with the community, discover new ideas and build your fashion network.',
    
    // Final CTA
    'finalCta.title': 'Ready to revolutionize your style?',
    'finalCta.subtitle': 'Join the FashionHub community',
    'finalCta.description': 'Thousands of fashionistas already share their passion. Your turn!',
    'finalCta.startButton': 'Create my wardrobe',
    'finalCta.exploreButton': 'Discover',

    // Creators page
    'creators.title': 'Fashion Creators',
    'creators.subtitle': 'Discover the fashionistas inspiring the community',
    'creators.searchPlaceholder': 'Search for a creator...',
    'creators.filterByStyle': 'Style',
    'creators.filterByLocation': 'Location',
    'creators.allStyles': 'All styles',
    'creators.allLocations': 'All cities',
    'creators.style.minimalist': 'Minimalist',
    'creators.style.streetwear': 'Streetwear',
    'creators.style.classic': 'Classic',
    'creators.style.bohemian': 'Bohemian',
    'creators.style.vintage': 'Vintage',
    'creators.style.luxury': 'Luxury',
    'creators.looks': 'looks',
    'creators.followers': 'followers',
    'creators.follow': 'Follow',
    'creators.following': 'Following',
    'creators.verified': 'Verified',
    'creators.viewProfile': 'View profile',
    
    // Collections page
    'collections.title': 'My Collections',
    'collections.subtitle': 'Organize your favorite looks by theme',
    'collections.myCollections': 'My Collections',
    'collections.savedLooks': 'Saved Looks',
    'collections.create': 'Create a collection',
    'collections.createNew': 'New collection',
    'collections.name': 'Collection name',
    'collections.namePlaceholder': 'E.g: Summer Looks 2024',
    'collections.description': 'Description',
    'collections.descriptionPlaceholder': 'Describe the theme of your collection...',
    'collections.visibility': 'Visibility',
    'collections.public': 'Public',
    'collections.private': 'Private',
    'collections.cancel': 'Cancel',
    'collections.save': 'Create',
    'collections.empty': 'No collections yet',
    'collections.emptyDescription': 'Create your first collection to start organizing your favorite looks.',
    'collections.items': 'looks',
    'collections.viewCollection': 'View collection',
    'collections.loginRequired': 'Login required',
    'collections.loginMessage': 'Sign in to access your collections',
    'collections.login': 'Sign in',

    // Concept page
    'concept.badge': 'The social network of fashion and style',
    'concept.title': 'Your virtual wardrobe,',
    'concept.titlePart2': 'your fashion community',
    'concept.subtitle': 'Create your online wardrobe, compose stylish looks,',
    'concept.subtitlePart2': 'and share your passion for fashion with an inspiring community.',
    'concept.feature.wardrobe': 'Virtual wardrobe',
    'concept.feature.wardrobeDesc': 'Organize your wardrobe',
    'concept.feature.createLooks': 'Create looks',
    'concept.feature.createLooksDesc': 'Creative mix & match',
    'concept.feature.community': 'Fashion community',
    'concept.feature.communityDesc': 'Share and inspire',
    'concept.feature.aiAssistant': 'AI Assistant',
    'concept.feature.aiAssistantDesc': 'Personalized suggestions',
    'concept.createDressing': 'Create my wardrobe',
    'concept.exploreLooks': 'Explore looks',
    'concept.stats.users': 'Active users',
    'concept.stats.looks': 'Looks shared',
    'concept.stats.items': 'Items cataloged',
    'concept.stats.collections': 'Collections created',
    'concept.whyTitle': 'Why FashionHub?',
    'concept.whySubtitle': 'Much more than just a virtual wardrobe',
    
    // Profile page
    'profile.notAuthenticated': 'Not authenticated',
    'profile.notAuthenticatedMessage': 'You must sign in to access your profile.',
    'profile.login': 'Sign in',
    'profile.myWardrobe': 'My Wardrobe',
    'profile.addItem': 'Add item',
    'profile.stats.items': 'Items',
    'profile.stats.looks': 'Looks',
    'profile.stats.followers': 'Followers',
    'profile.emptyWardrobe': 'Your wardrobe is empty',
    'profile.emptyWardrobeMessage': 'Start adding your clothes to create your virtual wardrobe.',
    
    // Feed page
    'feed.title': 'Fashion Feed',
    'feed.searchPlaceholder': 'Search for a style, color...',
    'feed.addLook': 'Add a look',
    'feed.allLooks': 'All looks',
    'feed.trending': 'Trending',
    'feed.following': 'Following',

    // Legal page
    'legal.title': 'Legal Notice & Privacy Policy',
    'legal.lastUpdate': 'Last update',
    'legal.editor.title': 'Site publisher',
    'legal.editor.company': 'Company name',
    'legal.editor.address': 'Address',
    'legal.editor.email': 'Email',
    'legal.editor.director': 'Publication director',
    'legal.hosting.title': 'Hosting',
    'legal.hosting.host': 'Host',
    'legal.hosting.address': 'Address',
    'legal.data.title': 'Personal data collection',
    'legal.data.intro': 'As part of using our platform, we collect the following data:',
    'legal.data.name': 'First and last name',
    'legal.data.email': 'Email address',
    'legal.data.photos': 'Photos of clothes and looks you share',
    'legal.data.profile': 'Profile information (bio, style tags)',
    'legal.data.navigation': 'Navigation data (technical cookies)',
    'legal.usage.title': 'Data usage',
    'legal.usage.intro': 'Your personal data is used to:',
    'legal.usage.account': 'Create and manage your user account',
    'legal.usage.wardrobe': 'Organize your virtual wardrobe',
    'legal.usage.share': 'Share your looks with the community',
    'legal.usage.recommendations': 'Personalize your style recommendations',
    'legal.usage.improve': 'Improve our services',
    'legal.usage.notifications': 'Send you important notifications',
    'legal.rights.title': 'Your rights',
    'legal.rights.intro': 'In accordance with GDPR, you have the following rights:',
    'legal.rights.access': 'Right of access to your data',
    'legal.rights.rectification': 'Right of rectification',
    'legal.rights.erasure': 'Right to erasure',
    'legal.rights.portability': 'Right to data portability',
    'legal.rights.objection': 'Right to object',
    'legal.rights.contact': 'To exercise these rights, contact us at:',
    'legal.terms.title': 'Terms of Use',
    'legal.terms.article1.title': 'Article 1 - Purpose',
    'legal.terms.article1.content': 'FashionHub is a social network dedicated to fashion and personal style. The platform allows users to create their virtual wardrobe, compose looks and share their passion for fashion.',
    'legal.terms.article2.title': 'Article 2 - Services',
    'legal.terms.article2.intro': 'We offer the following services:',
    'legal.terms.article2.service1': 'Creation and management of a virtual wardrobe',
    'legal.terms.article2.service2': 'Creation and sharing of looks',
    'legal.terms.article2.service3': 'Community interaction (likes, comments, subscriptions)',
    'legal.terms.article2.service4': 'Personalized thematic collections',
    'legal.terms.article2.service5': 'Style suggestions by artificial intelligence',
    'legal.terms.article3.title': 'Article 3 - Responsibilities',
    'legal.terms.article3.content': 'FashionHub acts as a content hosting platform. Users are solely responsible for the content they publish and must respect copyright and intellectual property.',
    'legal.terms.article4.title': 'Article 4 - Pricing',
    'legal.terms.article4.content': 'Registration and use of FashionHub are completely free. No hidden fees are charged to users.',
    'legal.terms.article5.title': 'Article 5 - Content',
    'legal.terms.article5.content': 'By publishing content on FashionHub, you grant the platform a non-exclusive license to display, distribute and promote your content. You retain all your intellectual property rights.',
    'legal.terms.article6.title': 'Article 6 - Moderation',
    'legal.terms.article6.content': 'FashionHub reserves the right to moderate and remove any inappropriate, offensive or contrary content to our terms of use.',
    'legal.cookies.title': 'Cookies',
    'legal.cookies.content': 'Our site uses only technical cookies necessary for the platform to function (authentication, user preferences). No advertising or tracking cookies are used.',
    'legal.ip.title': 'Intellectual Property',
    'legal.ip.content': 'The design, logo and all graphic elements of FashionHub are protected by copyright. Any reproduction without authorization is prohibited.',
    'legal.contact.title': 'Contact',
    'legal.contact.content': 'For any questions regarding our legal notice or privacy policy, contact us at:',
    
    // Messages page
    'messages.title': 'Messages',
    'messages.subtitle': 'Communicate with your clients and providers',
    'messages.loginRequired': 'Login required',
    'messages.loginMessage': 'Sign in to access your messages',
    'messages.searchPlaceholder': 'Search for a conversation...',
    'messages.noConversations': 'No conversations',
    'messages.startConversation': 'Start chatting with other members',
    'messages.typeMessage': 'Type your message...',
    'messages.send': 'Send',
  },
  es: {
    // Navbar
    'navbar.login': 'Iniciar sesión',
    'navbar.register': 'Crear cuenta',
    'navbar.registerShort': 'Registrarse',
    'navbar.marketplace': 'Mercado (en pausa)',
    'navbar.myMissions': 'Mis Misiones',
    'navbar.createMission': 'Crear Misión',
    'navbar.messages': 'Mensajes',
    'navbar.profile': 'Perfil',
    'navbar.dashboard': 'Panel',
    'navbar.favorites': 'Mis favoritos',
    'navbar.logout': 'Cerrar sesión',
    'navbar.newMission': 'Nueva misión',
    'navbar.mission': 'Misión',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'Tu red social de moda',
    'brand.taglinePart1': 'Tu red ',
    'brand.taglinePart2': 'social',
    'brand.taglinePart3': ' de moda',

    // Home page
    'home.title': 'La red social que revoluciona la moda',
    'home.subtitle': 'FashionHub conecta a los amantes de la moda en todo el mundo',
    'home.hero.title': 'Encuentra el proveedor perfecto con IA',
    'home.hero.description': 'Plataforma francesa de licitaciones inversas con inteligencia artificial.',
    'home.hero.platformLaunching': 'Plataforma en lanzamiento',
    'home.hero.earlyUsers': 'Primeros usuarios',
    'home.hero.discoverMissions': 'Descubrir misiones',
    'home.hero.postMission': 'Publicar una misión',
    'home.reverseAuction.title': 'Subasta inversa',
    'home.reverseAuction.description': 'En lugar de buscar proveedores, publica tu necesidad y deja que vengan a ti con sus mejores ofertas.',
    'home.reverseAuction.details': '¡No busques más el mejor precio, viene a ti!',
    'home.reverseAuction.result': 'Resultado: precios naturalmente más competitivos',
    'home.directContact.title': 'Contacto directo',
    'home.directContact.description': 'Acceso inmediato a expertos de la red y más allá',
    'home.networkValue.title': 'Monetiza tu red',
    'home.networkValue.description': 'Genera ingresos recomendando los contactos adecuados',
    'home.startButton': 'Comenzar',
    'home.ourApproach.title': 'Nuestro enfoque',
    'home.ourApproach.description': 'Mejoramos el modelo de conexión existente con dos mecanismos simples pero efectivos',
    'home.paidConnection.title': 'Conexión pagada',
    'home.paidConnection.description': 'En lugar de prospectar durante semanas, paga a alguien que ya tenga el contacto para conectarte directamente.',
    'home.paidConnection.result': 'Resultado: tu red se vuelve rentable, los contactos son inmediatos',
    'home.whyItWorks.title': 'Por qué funciona esta combinación',
    'home.whyItWorks.economical.title': 'Económicamente lógico',
    'home.whyItWorks.economical.description': 'La competencia optimiza los precios',
    'home.whyItWorks.efficient.title': 'Eficiente para todos',
    'home.whyItWorks.efficient.description': 'Menos búsqueda, más resultados',
    'home.whyItWorks.profitable.title': 'Red rentable',
    'home.whyItWorks.profitable.description': 'Cualquiera puede convertirse en intermediario de negocios',
    'home.whyItWorks.immediate.title': 'Contactos inmediatos',
    'home.whyItWorks.immediate.description': 'Se acabó la prospección prolongada',

    // Footer
    'footer.description': 'La plataforma que conecta talentos y oportunidades en todos los dominios. Encuentra el socio ideal para dar vida a tus proyectos.',
    'footer.madeWithPassion': 'Hecho con pasión',
    'footer.navigation': 'Navegación',
    'footer.discoverMissions': 'Descubrir misiones',
    'footer.findExperts': 'Encontrar expertos',
    'footer.publishMission': 'Publicar una misión',
    'footer.ourConcept': 'Nuestro concepto',
    'footer.mySpace': 'Mi Espacio',
    'footer.myDashboard': 'Mi panel',
    'footer.myProfile': 'Mi perfil',
    'footer.support': 'Soporte',
    'footer.legalNotices': 'Avisos legales',
    'footer.sitemap': 'Mapa del sitio',
    'footer.rightsReserved': '© 2024 FashionHub. Todos los derechos reservados.',
    'footer.service247': 'Servicio disponible 24/7',
    'footer.globalPlatform': '🌍 Plataforma global',
    'footer.securePayments': '🔒 Pagos seguros',

    // Mobile navigation
    'mobile.navigation': 'Navegación',
    'mobile.feed': 'Feed',
    'mobile.providers': 'Proveedores',
    'mobile.services': 'Servicios',
    'mobile.concept': 'Nuestro concepto',
    'mobile.missions': 'Misiones',
    'mobile.mySpace': 'Mi Espacio',
    'mobile.myFavorites': 'Mis favoritos',
    'mobile.collections': 'Colecciones',
    'mobile.creators': 'Creadores',
    'mobile.explore': 'Explorar',
    'mobile.new': 'Nuevo',

    // Home page - FashionHub
    'home.fashionhub.badge': 'Red Social de Moda',
    'home.fashionhub.title': 'FashionHub',
    'home.fashionhub.subtitle': 'Crea tu guardarropa virtual, comparte tus looks, inspira a la comunidad',
    'home.fashionhub.description': 'Organiza tu guardarropa, compone outfits y conecta con amantes de la moda.',
    'home.fashionhub.startDressing': 'Comenzar mi guardarropa',
    'home.fashionhub.exploreTrends': 'Explorar tendencias',
    'home.fashionhub.viewFeed': 'Ver feed',
    
    // Features page
    'features.badge': 'Funcionalidades Completas',
    'features.title': 'Descubre todo lo que FashionHub puede hacer por tu estilo',
    'features.subtitle': 'Una plataforma completa con funcionalidades avanzadas para organizar tu guardarropa, crear looks con estilo y compartir tu pasión por la moda.',
    'features.startNow': 'Comenzar ahora',
    'features.fashionistas': 'Fashionistas activos',
    'features.looksShared': 'Looks compartidos',
    'features.satisfaction': 'Tasa de satisfacción',
    'features.itemsCataloged': 'Artículos catalogados',
    'features.wardrobe.title': 'Guardarropa Virtual',
    'features.wardrobe.description': 'Cataloga toda tu ropa con fotos. Organiza por categoría, color, temporada.',
    'features.looks.title': 'Creación de Looks',
    'features.looks.description': 'Combina tus artículos para crear outfits completos y compártelos.',
    'features.feed.title': 'Feed Inspirador',
    'features.feed.description': 'Descubre looks de tendencia y guarda tus outfits favoritos.',
    'features.community.title': 'Comunidad de Moda',
    'features.community.description': 'Conecta con otros entusiastas y comparte tu pasión por el estilo.',
    'features.collections.title': 'Colecciones Temáticas',
    'features.collections.description': 'Crea tableros para organizar tus looks por ocasión o estilo.',
    'features.ai.title': 'Sugerencias IA',
    'features.ai.description': 'Descubre nuevas formas de usar lo que ya tienes.',
    'features.carousel.prev': 'Anterior',
    'features.carousel.next': 'Siguiente',
    
    // How it works section
    'howItWorks.title': '¿Cómo funciona?',
    'howItWorks.subtitle': 'Tres pasos simples para revolucionar cómo manejas tu estilo',
    'howItWorks.step1.title': 'Cataloga tu guardarropa',
    'howItWorks.step1.description': 'Toma fotos de toda tu ropa y accesorios. Agrégalos a tu guardarropa virtual con sus características.',
    'howItWorks.step2.title': 'Crea tus looks',
    'howItWorks.step2.description': 'Combina tus artículos para crear outfits. Visualiza tus looks y comparte tus mejores creaciones.',
    'howItWorks.step3.title': 'Inspira y conecta',
    'howItWorks.step3.description': 'Comparte con la comunidad, descubre nuevas ideas y construye tu red de moda.',
    
    // Final CTA
    'finalCta.title': '¿Listo para revolucionar tu estilo?',
    'finalCta.subtitle': 'Únete a la comunidad FashionHub',
    'finalCta.description': '¡Miles de fashionistas ya comparten su pasión. Tu turno!',
    'finalCta.startButton': 'Crear mi guardarropa',
    'finalCta.exploreButton': 'Descubrir',

    // Creators page
    'creators.title': 'Creadores de Moda',
    'creators.subtitle': 'Descubre a las fashionistas que inspiran a la comunidad',
    'creators.searchPlaceholder': 'Buscar un creador...',
    'creators.filterByStyle': 'Estilo',
    'creators.filterByLocation': 'Ubicación',
    'creators.allStyles': 'Todos los estilos',
    'creators.allLocations': 'Todas las ciudades',
    'creators.style.minimalist': 'Minimalista',
    'creators.style.streetwear': 'Streetwear',
    'creators.style.classic': 'Clásico',
    'creators.style.bohemian': 'Bohemio',
    'creators.style.vintage': 'Vintage',
    'creators.style.luxury': 'Lujo',
    'creators.looks': 'looks',
    'creators.followers': 'seguidores',
    'creators.follow': 'Seguir',
    'creators.following': 'Siguiendo',
    'creators.verified': 'Verificado',
    'creators.viewProfile': 'Ver perfil',
    
    // Collections page
    'collections.title': 'Mis Colecciones',
    'collections.subtitle': 'Organiza tus looks favoritos por tema',
    'collections.myCollections': 'Mis Colecciones',
    'collections.savedLooks': 'Looks Guardados',
    'collections.create': 'Crear una colección',
    'collections.createNew': 'Nueva colección',
    'collections.name': 'Nombre de la colección',
    'collections.namePlaceholder': 'Ej: Looks de Verano 2024',
    'collections.description': 'Descripción',
    'collections.descriptionPlaceholder': 'Describe el tema de tu colección...',
    'collections.visibility': 'Visibilidad',
    'collections.public': 'Público',
    'collections.private': 'Privado',
    'collections.cancel': 'Cancelar',
    'collections.save': 'Crear',
    'collections.empty': 'Aún no hay colecciones',
    'collections.emptyDescription': 'Crea tu primera colección para comenzar a organizar tus looks favoritos.',
    'collections.items': 'looks',
    'collections.viewCollection': 'Ver colección',
    'collections.loginRequired': 'Inicio de sesión requerido',
    'collections.loginMessage': 'Inicia sesión para acceder a tus colecciones',
    'collections.login': 'Iniciar sesión',

    // Concept page
    'concept.badge': 'La red social de la moda y el estilo',
    'concept.title': 'Tu guardarropa virtual,',
    'concept.titlePart2': 'tu comunidad de moda',
    'concept.subtitle': 'Crea tu guardarropa en línea, compone looks con estilo,',
    'concept.subtitlePart2': 'y comparte tu pasión por la moda con una comunidad inspiradora.',
    'concept.feature.wardrobe': 'Guardarropa virtual',
    'concept.feature.wardrobeDesc': 'Organiza tu guardarropa',
    'concept.feature.createLooks': 'Crea looks',
    'concept.feature.createLooksDesc': 'Mix & match creativo',
    'concept.feature.community': 'Comunidad de moda',
    'concept.feature.communityDesc': 'Comparte e inspira',
    'concept.feature.aiAssistant': 'Asistente IA',
    'concept.feature.aiAssistantDesc': 'Sugerencias personalizadas',
    'concept.createDressing': 'Crear mi guardarropa',
    'concept.exploreLooks': 'Explorar looks',
    'concept.stats.users': 'Usuarios activos',
    'concept.stats.looks': 'Looks compartidos',
    'concept.stats.items': 'Artículos catalogados',
    'concept.stats.collections': 'Colecciones creadas',
    'concept.whyTitle': '¿Por qué FashionHub?',
    'concept.whySubtitle': 'Mucho más que un simple guardarropa virtual',
    
    // Profile page
    'profile.notAuthenticated': 'No autenticado',
    'profile.notAuthenticatedMessage': 'Debes iniciar sesión para acceder a tu perfil.',
    'profile.login': 'Iniciar sesión',
    'profile.myWardrobe': 'Mi Guardarropa',
    'profile.addItem': 'Agregar artículo',
    'profile.stats.items': 'Artículos',
    'profile.stats.looks': 'Looks',
    'profile.stats.followers': 'Seguidores',
    'profile.emptyWardrobe': 'Tu guardarropa está vacío',
    'profile.emptyWardrobeMessage': 'Comienza a agregar tu ropa para crear tu guardarropa virtual.',
    
    // Feed page
    'feed.title': 'Feed de Moda',
    'feed.searchPlaceholder': 'Buscar un estilo, color...',
    'feed.addLook': 'Agregar un look',
    'feed.allLooks': 'Todos los looks',
    'feed.trending': 'Tendencias',
    'feed.following': 'Siguiendo',

    // Legal page
    'legal.title': 'Aviso Legal & Política de Privacidad',
    'legal.lastUpdate': 'Última actualización',
    'legal.editor.title': 'Editor del sitio',
    'legal.editor.company': 'Nombre de la empresa',
    'legal.editor.address': 'Dirección',
    'legal.editor.email': 'Email',
    'legal.editor.director': 'Director de publicación',
    'legal.hosting.title': 'Alojamiento',
    'legal.hosting.host': 'Proveedor de alojamiento',
    'legal.hosting.address': 'Dirección',
    'legal.data.title': 'Recopilación de datos personales',
    'legal.data.intro': 'Como parte del uso de nuestra plataforma, recopilamos los siguientes datos:',
    'legal.data.name': 'Nombre y apellido',
    'legal.data.email': 'Dirección de correo electrónico',
    'legal.data.photos': 'Fotos de ropa y looks que compartes',
    'legal.data.profile': 'Información de perfil (biografía, etiquetas de estilo)',
    'legal.data.navigation': 'Datos de navegación (cookies técnicas)',
    'legal.usage.title': 'Uso de datos',
    'legal.usage.intro': 'Tus datos personales se utilizan para:',
    'legal.usage.account': 'Crear y gestionar tu cuenta de usuario',
    'legal.usage.wardrobe': 'Organizar tu guardarropa virtual',
    'legal.usage.share': 'Compartir tus looks con la comunidad',
    'legal.usage.recommendations': 'Personalizar tus recomendaciones de estilo',
    'legal.usage.improve': 'Mejorar nuestros servicios',
    'legal.usage.notifications': 'Enviarte notificaciones importantes',
    'legal.rights.title': 'Tus derechos',
    'legal.rights.intro': 'De acuerdo con el RGPD, tienes los siguientes derechos:',
    'legal.rights.access': 'Derecho de acceso a tus datos',
    'legal.rights.rectification': 'Derecho de rectificación',
    'legal.rights.erasure': 'Derecho al borrado',
    'legal.rights.portability': 'Derecho a la portabilidad de datos',
    'legal.rights.objection': 'Derecho de oposición',
    'legal.rights.contact': 'Para ejercer estos derechos, contáctanos en:',
    'legal.terms.title': 'Condiciones Generales de Uso',
    'legal.terms.article1.title': 'Artículo 1 - Propósito',
    'legal.terms.article1.content': 'FashionHub es una red social dedicada a la moda y el estilo personal. La plataforma permite a los usuarios crear su guardarropa virtual, componer looks y compartir su pasión por la moda.',
    'legal.terms.article2.title': 'Artículo 2 - Servicios',
    'legal.terms.article2.intro': 'Ofrecemos los siguientes servicios:',
    'legal.terms.article2.service1': 'Creación y gestión de un guardarropa virtual',
    'legal.terms.article2.service2': 'Creación y compartición de looks',
    'legal.terms.article2.service3': 'Interacción con la comunidad (me gusta, comentarios, suscripciones)',
    'legal.terms.article2.service4': 'Colecciones temáticas personalizadas',
    'legal.terms.article2.service5': 'Sugerencias de estilo por inteligencia artificial',
    'legal.terms.article3.title': 'Artículo 3 - Responsabilidades',
    'legal.terms.article3.content': 'FashionHub actúa como una plataforma de alojamiento de contenido. Los usuarios son los únicos responsables del contenido que publican y deben respetar los derechos de autor y la propiedad intelectual.',
    'legal.terms.article4.title': 'Artículo 4 - Precios',
    'legal.terms.article4.content': 'El registro y uso de FashionHub son completamente gratuitos. No se cobran tarifas ocultas a los usuarios.',
    'legal.terms.article5.title': 'Artículo 5 - Contenido',
    'legal.terms.article5.content': 'Al publicar contenido en FashionHub, otorgas a la plataforma una licencia no exclusiva para mostrar, distribuir y promover tu contenido. Conservas todos tus derechos de propiedad intelectual.',
    'legal.terms.article6.title': 'Artículo 6 - Moderación',
    'legal.terms.article6.content': 'FashionHub se reserva el derecho de moderar y eliminar cualquier contenido inapropiado, ofensivo o contrario a nuestros términos de uso.',
    'legal.cookies.title': 'Cookies',
    'legal.cookies.content': 'Nuestro sitio utiliza solo cookies técnicas necesarias para el funcionamiento de la plataforma (autenticación, preferencias de usuario). No se utilizan cookies publicitarias o de seguimiento.',
    'legal.ip.title': 'Propiedad Intelectual',
    'legal.ip.content': 'El diseño, el logo y todos los elementos gráficos de FashionHub están protegidos por derechos de autor. Toda reproducción sin autorización está prohibida.',
    'legal.contact.title': 'Contacto',
    'legal.contact.content': 'Para cualquier pregunta sobre nuestro aviso legal o política de privacidad, contáctanos en:',
    
    // Messages page
    'messages.title': 'Mensajes',
    'messages.subtitle': 'Comunícate con tus clientes y proveedores',
    'messages.loginRequired': 'Inicio de sesión requerido',
    'messages.loginMessage': 'Inicia sesión para acceder a tus mensajes',
    'messages.searchPlaceholder': 'Buscar una conversación...',
    'messages.noConversations': 'Sin conversaciones',
    'messages.startConversation': 'Comienza a chatear con otros miembros',
    'messages.typeMessage': 'Escribe tu mensaje...',
    'messages.send': 'Enviar',
  },
  ar: {
    // Navbar
    'navbar.login': 'تسجيل الدخول',
    'navbar.register': 'إنشاء حساب',
    'navbar.registerShort': 'التسجيل',
    'navbar.marketplace': 'السوق (متوقف)',
    'navbar.myMissions': 'مهامي',
    'navbar.createMission': 'إنشاء مهمة',
    'navbar.messages': 'الرسائل',
    'navbar.profile': 'الملف الشخصي',
    'navbar.dashboard': 'لوحة التحكم',
    'navbar.favorites': 'المفضلة',
    'navbar.logout': 'تسجيل الخروج',
    'navbar.newMission': 'مهمة جديدة',
    'navbar.mission': 'مهمة',

    // Brand
    'brand.name': 'FashionHub',
    'brand.tagline': 'شبكتك الاجتماعية للموضة',
    'brand.taglinePart1': 'شبكتك ',
    'brand.taglinePart2': 'الاجتماعية',
    'brand.taglinePart3': ' للموضة',

    // Home page
    'home.title': 'الشبكة الاجتماعية التي تحدث ثورة في الموضة',
    'home.subtitle': 'FashionHub يربط عشاق الموضة حول العالم',
    'home.hero.title': 'ابحث عن مزود الخدمة المثالي بالذكاء الاصطناعي',
    'home.hero.description': 'منصة فرنسية للمناقصات العكسية بالذكاء الاصطناعي.',
    'home.hero.platformLaunching': 'إطلاق المنصة',
    'home.hero.earlyUsers': 'المستخدمون الأوائل',
    'home.hero.discoverMissions': 'اكتشف المهام',
    'home.hero.postMission': 'نشر مهمة',
    'home.reverseAuction.title': 'مزاد عكسي',
    'home.reverseAuction.description': 'بدلاً من البحث عن مزودي الخدمات، انشر احتياجك ودعهم يأتون إليك بأفضل عروضهم.',
    'home.reverseAuction.details': 'لا تبحث عن أفضل سعر، سيأتي إليك!',
    'home.reverseAuction.result': 'النتيجة: أسعار أكثر تنافسية بشكل طبيعي',
    'home.directContact.title': 'اتصال مباشر',
    'home.directContact.description': 'وصول فوري إلى خبراء الشبكة وما بعدها',
    'home.networkValue.title': 'استثمر شبكتك',
    'home.networkValue.description': 'حقق دخلاً من خلال التوصية بجهات الاتصال المناسبة',
    'home.startButton': 'ابدأ',
    'home.ourApproach.title': 'نهجنا',
    'home.ourApproach.description': 'نحسن نموذج الاتصال الحالي بآليتين بسيطتين ولكن فعالتين',
    'home.paidConnection.title': 'اتصال مدفوع',
    'home.paidConnection.description': 'بدلاً من التنقيب لأسابيع، ادفع لشخص لديه جهة الاتصال بالفعل ليوصلك مباشرة.',
    'home.paidConnection.result': 'النتيجة: شبكتك تصبح مربحة، جهات الاتصال فورية',
    'home.whyItWorks.title': 'لماذا يعمل هذا المزيج',
    'home.whyItWorks.economical.title': 'منطقي اقتصادياً',
    'home.whyItWorks.economical.description': 'المنافسة تحسن الأسعار',
    'home.whyItWorks.efficient.title': 'فعال للجميع',
    'home.whyItWorks.efficient.description': 'بحث أقل، نتائج أكثر',
    'home.whyItWorks.profitable.title': 'شبكة مربحة',
    'home.whyItWorks.profitable.description': 'يمكن لأي شخص أن يصبح وسيط أعمال',
    'home.whyItWorks.immediate.title': 'جهات اتصال فورية',
    'home.whyItWorks.immediate.description': 'انتهى التنقيب الطويل',

    // Footer
    'footer.description': 'المنصة التي تربط المواهب والفرص في جميع المجالات. ابحث عن الشريك المثالي لإحياء مشاريعك.',
    'footer.madeWithPassion': 'صُنع بشغف',
    'footer.navigation': 'التنقل',
    'footer.discoverMissions': 'اكتشف المهام',
    'footer.findExperts': 'ابحث عن خبراء',
    'footer.publishMission': 'نشر مهمة',
    'footer.ourConcept': 'مفهومنا',
    'footer.mySpace': 'مساحتي',
    'footer.myDashboard': 'لوحة التحكم',
    'footer.myProfile': 'ملفي الشخصي',
    'footer.support': 'الدعم',
    'footer.legalNotices': 'الإشعارات القانونية',
    'footer.sitemap': 'خريطة الموقع',
    'footer.rightsReserved': '© 2024 FashionHub. جميع الحقوق محفوظة.',
    'footer.service247': 'خدمة متاحة 24/7',
    'footer.globalPlatform': '🌍 منصة عالمية',
    'footer.securePayments': '🔒 مدفوعات آمنة',

    // Mobile navigation
    'mobile.navigation': 'التنقل',
    'mobile.feed': 'التغذية',
    'mobile.providers': 'مزودو الخدمات',
    'mobile.services': 'الخدمات',
    'mobile.concept': 'مفهومنا',
    'mobile.missions': 'المهام',
    'mobile.mySpace': 'مساحتي',
    'mobile.myFavorites': 'المفضلة',
    'mobile.collections': 'المجموعات',
    'mobile.creators': 'المبدعون',
    'mobile.explore': 'استكشف',
    'mobile.new': 'جديد',

    // Home page - FashionHub
    'home.fashionhub.badge': 'الشبكة الاجتماعية للموضة',
    'home.fashionhub.title': 'FashionHub',
    'home.fashionhub.subtitle': 'أنشئ خزانة ملابسك الافتراضية، شارك إطلالاتك، ألهم المجتمع',
    'home.fashionhub.description': 'نظم خزانة ملابسك، صمم الأزياء وتواصل مع عشاق الموضة.',
    'home.fashionhub.startDressing': 'ابدأ خزانة ملابسي',
    'home.fashionhub.exploreTrends': 'استكشف الاتجاهات',
    'home.fashionhub.viewFeed': 'عرض التغذية',
    
    // Features page
    'features.badge': 'ميزات كاملة',
    'features.title': 'اكتشف كل ما يمكن أن يفعله FashionHub لأسلوبك',
    'features.subtitle': 'منصة كاملة مع ميزات متقدمة لتنظيم خزانة ملابسك، وإنشاء إطلالات أنيقة ومشاركة شغفك بالموضة.',
    'features.startNow': 'ابدأ الآن',
    'features.fashionistas': 'عشاق الموضة النشطون',
    'features.looksShared': 'الإطلالات المشتركة',
    'features.satisfaction': 'معدل الرضا',
    'features.itemsCataloged': 'العناصر المفهرسة',
    'features.wardrobe.title': 'خزانة افتراضية',
    'features.wardrobe.description': 'فهرس جميع ملابسك مع الصور. نظم حسب الفئة واللون والموسم.',
    'features.looks.title': 'إنشاء الإطلالات',
    'features.looks.description': 'اجمع عناصرك لإنشاء أزياء كاملة وشاركها.',
    'features.feed.title': 'تغذية ملهمة',
    'features.feed.description': 'اكتشف إطلالات رائجة واحفظ أزياءك المفضلة.',
    'features.community.title': 'مجتمع الموضة',
    'features.community.description': 'تواصل مع محبين آخرين وشارك شغفك بالأسلوب.',
    'features.collections.title': 'مجموعات موضوعية',
    'features.collections.description': 'أنشئ لوحات لتنظيم إطلالاتك حسب المناسبة أو الأسلوب.',
    'features.ai.title': 'اقتراحات الذكاء الاصطناعي',
    'features.ai.description': 'اكتشف طرقًا جديدة لارتداء ما لديك بالفعل.',
    'features.carousel.prev': 'السابق',
    'features.carousel.next': 'التالي',
    
    // How it works section
    'howItWorks.title': 'كيف يعمل؟',
    'howItWorks.subtitle': 'ثلاث خطوات بسيطة لإحداث ثورة في كيفية إدارة أسلوبك',
    'howItWorks.step1.title': 'فهرس خزانة ملابسك',
    'howItWorks.step1.description': 'التقط صورًا لجميع ملابسك وإكسسواراتك. أضفها إلى خزانة ملابسك الافتراضية مع ميزاتها.',
    'howItWorks.step2.title': 'أنشئ إطلالاتك',
    'howItWorks.step2.description': 'اجمع عناصرك لإنشاء الأزياء. تصور إطلالاتك وشارك أفضل إبداعاتك.',
    'howItWorks.step3.title': 'ألهم وتواصل',
    'howItWorks.step3.description': 'شارك مع المجتمع، اكتشف أفكارًا جديدة وابنِ شبكتك للموضة.',
    
    // Final CTA
    'finalCta.title': 'هل أنت مستعد لإحداث ثورة في أسلوبك؟',
    'finalCta.subtitle': 'انضم إلى مجتمع FashionHub',
    'finalCta.description': 'الآلاف من عشاق الموضة يشاركون شغفهم بالفعل. دورك!',
    'finalCta.startButton': 'أنشئ خزانة ملابسي',
    'finalCta.exploreButton': 'اكتشف',

    // Creators page
    'creators.title': 'مبدعو الموضة',
    'creators.subtitle': 'اكتشف عشاق الموضة الذين يلهمون المجتمع',
    'creators.searchPlaceholder': 'ابحث عن مبدع...',
    'creators.filterByStyle': 'الأسلوب',
    'creators.filterByLocation': 'الموقع',
    'creators.allStyles': 'جميع الأساليب',
    'creators.allLocations': 'جميع المدن',
    'creators.style.minimalist': 'بسيط',
    'creators.style.streetwear': 'ستريت وير',
    'creators.style.classic': 'كلاسيكي',
    'creators.style.bohemian': 'بوهيمي',
    'creators.style.vintage': 'عتيق',
    'creators.style.luxury': 'فاخر',
    'creators.looks': 'إطلالات',
    'creators.followers': 'متابعون',
    'creators.follow': 'متابعة',
    'creators.following': 'متابَع',
    'creators.verified': 'موثق',
    'creators.viewProfile': 'عرض الملف الشخصي',
    
    // Collections page
    'collections.title': 'مجموعاتي',
    'collections.subtitle': 'نظم إطلالاتك المفضلة حسب الموضوع',
    'collections.myCollections': 'مجموعاتي',
    'collections.savedLooks': 'الإطلالات المحفوظة',
    'collections.create': 'إنشاء مجموعة',
    'collections.createNew': 'مجموعة جديدة',
    'collections.name': 'اسم المجموعة',
    'collections.namePlaceholder': 'مثال: إطلالات الصيف 2024',
    'collections.description': 'الوصف',
    'collections.descriptionPlaceholder': 'صف موضوع مجموعتك...',
    'collections.visibility': 'الرؤية',
    'collections.public': 'عام',
    'collections.private': 'خاص',
    'collections.cancel': 'إلغاء',
    'collections.save': 'إنشاء',
    'collections.empty': 'لا توجد مجموعات بعد',
    'collections.emptyDescription': 'أنشئ مجموعتك الأولى لتبدأ في تنظيم إطلالاتك المفضلة.',
    'collections.items': 'إطلالات',
    'collections.viewCollection': 'عرض المجموعة',
    'collections.loginRequired': 'تسجيل الدخول مطلوب',
    'collections.loginMessage': 'سجل الدخول للوصول إلى مجموعاتك',
    'collections.login': 'تسجيل الدخول',

    // Concept page
    'concept.badge': 'الشبكة الاجتماعية للموضة والأسلوب',
    'concept.title': 'خزانة ملابسك الافتراضية،',
    'concept.titlePart2': 'مجتمع الموضة الخاص بك',
    'concept.subtitle': 'أنشئ خزانة ملابسك عبر الإنترنت، صمم إطلالات أنيقة،',
    'concept.subtitlePart2': 'وشارك شغفك بالموضة مع مجتمع ملهم.',
    'concept.feature.wardrobe': 'خزانة افتراضية',
    'concept.feature.wardrobeDesc': 'نظم خزانة ملابسك',
    'concept.feature.createLooks': 'أنشئ إطلالات',
    'concept.feature.createLooksDesc': 'مزج وتنسيق إبداعي',
    'concept.feature.community': 'مجتمع الموضة',
    'concept.feature.communityDesc': 'شارك وألهم',
    'concept.feature.aiAssistant': 'مساعد الذكاء الاصطناعي',
    'concept.feature.aiAssistantDesc': 'اقتراحات شخصية',
    'concept.createDressing': 'أنشئ خزانة ملابسي',
    'concept.exploreLooks': 'استكشف الإطلالات',
    'concept.stats.users': 'مستخدمون نشطون',
    'concept.stats.looks': 'إطلالات مشتركة',
    'concept.stats.items': 'عناصر مفهرسة',
    'concept.stats.collections': 'مجموعات تم إنشاؤها',
    'concept.whyTitle': 'لماذا FashionHub؟',
    'concept.whySubtitle': 'أكثر بكثير من مجرد خزانة افتراضية',
    
    // Profile page
    'profile.notAuthenticated': 'غير مصادق عليه',
    'profile.notAuthenticatedMessage': 'يجب عليك تسجيل الدخول للوصول إلى ملفك الشخصي.',
    'profile.login': 'تسجيل الدخول',
    'profile.myWardrobe': 'خزانة ملابسي',
    'profile.addItem': 'إضافة عنصر',
    'profile.stats.items': 'عناصر',
    'profile.stats.looks': 'إطلالات',
    'profile.stats.followers': 'متابعون',
    'profile.emptyWardrobe': 'خزانة ملابسك فارغة',
    'profile.emptyWardrobeMessage': 'ابدأ بإضافة ملابسك لإنشاء خزانة ملابسك الافتراضية.',
    
    // Feed page
    'feed.title': 'تغذية الموضة',
    'feed.searchPlaceholder': 'ابحث عن أسلوب، لون...',
    'feed.addLook': 'إضافة إطلالة',
    'feed.allLooks': 'جميع الإطلالات',
    'feed.trending': 'الاتجاهات',
    'feed.following': 'المتابَعون',

    // Legal page
    'legal.title': 'الإشعار القانوني وسياسة الخصوصية',
    'legal.lastUpdate': 'آخر تحديث',
    'legal.editor.title': 'ناشر الموقع',
    'legal.editor.company': 'اسم الشركة',
    'legal.editor.address': 'العنوان',
    'legal.editor.email': 'البريد الإلكتروني',
    'legal.editor.director': 'مدير النشر',
    'legal.hosting.title': 'الاستضافة',
    'legal.hosting.host': 'مزود الاستضافة',
    'legal.hosting.address': 'العنوان',
    'legal.data.title': 'جمع البيانات الشخصية',
    'legal.data.intro': 'كجزء من استخدام منصتنا، نجمع البيانات التالية:',
    'legal.data.name': 'الاسم الأول والأخير',
    'legal.data.email': 'عنوان البريد الإلكتروني',
    'legal.data.photos': 'صور الملابس والإطلالات التي تشاركها',
    'legal.data.profile': 'معلومات الملف الشخصي (السيرة الذاتية، علامات الأسلوب)',
    'legal.data.navigation': 'بيانات التنقل (ملفات تعريف الارتباط التقنية)',
    'legal.usage.title': 'استخدام البيانات',
    'legal.usage.intro': 'تُستخدم بياناتك الشخصية من أجل:',
    'legal.usage.account': 'إنشاء وإدارة حساب المستخدم الخاص بك',
    'legal.usage.wardrobe': 'تنظيم خزانة ملابسك الافتراضية',
    'legal.usage.share': 'مشاركة إطلالاتك مع المجتمع',
    'legal.usage.recommendations': 'تخصيص توصيات الأسلوب الخاصة بك',
    'legal.usage.improve': 'تحسين خدماتنا',
    'legal.usage.notifications': 'إرسال إشعارات مهمة لك',
    'legal.rights.title': 'حقوقك',
    'legal.rights.intro': 'وفقًا للائحة العامة لحماية البيانات، لديك الحقوق التالية:',
    'legal.rights.access': 'حق الوصول إلى بياناتك',
    'legal.rights.rectification': 'حق التصحيح',
    'legal.rights.erasure': 'حق المحو',
    'legal.rights.portability': 'حق نقل البيانات',
    'legal.rights.objection': 'حق الاعتراض',
    'legal.rights.contact': 'لممارسة هذه الحقوق، اتصل بنا على:',
    'legal.terms.title': 'شروط الاستخدام',
    'legal.terms.article1.title': 'المادة 1 - الغرض',
    'legal.terms.article1.content': 'FashionHub هي شبكة اجتماعية مخصصة للموضة والأسلوب الشخصي. تتيح المنصة للمستخدمين إنشاء خزانة ملابسهم الافتراضية وتصميم الإطلالات ومشاركة شغفهم بالموضة.',
    'legal.terms.article2.title': 'المادة 2 - الخدمات',
    'legal.terms.article2.intro': 'نقدم الخدمات التالية:',
    'legal.terms.article2.service1': 'إنشاء وإدارة خزانة ملابس افتراضية',
    'legal.terms.article2.service2': 'إنشاء ومشاركة الإطلالات',
    'legal.terms.article2.service3': 'التفاعل مع المجتمع (إعجابات، تعليقات، اشتراكات)',
    'legal.terms.article2.service4': 'مجموعات موضوعية شخصية',
    'legal.terms.article2.service5': 'اقتراحات الأسلوب بواسطة الذكاء الاصطناعي',
    'legal.terms.article3.title': 'المادة 3 - المسؤوليات',
    'legal.terms.article3.content': 'يعمل FashionHub كمنصة استضافة محتوى. المستخدمون وحدهم مسؤولون عن المحتوى الذي ينشرونه ويجب عليهم احترام حقوق النشر والملكية الفكرية.',
    'legal.terms.article4.title': 'المادة 4 - الأسعار',
    'legal.terms.article4.content': 'التسجيل واستخدام FashionHub مجانيان تمامًا. لا توجد رسوم مخفية يتم تطبيقها على المستخدمين.',
    'legal.terms.article5.title': 'المادة 5 - المحتوى',
    'legal.terms.article5.content': 'من خلال نشر المحتوى على FashionHub، فإنك تمنح المنصة ترخيصًا غير حصري لعرض المحتوى الخاص بك وتوزيعه والترويج له. تحتفظ بجميع حقوق الملكية الفكرية الخاصة بك.',
    'legal.terms.article6.title': 'المادة 6 - الإشراف',
    'legal.terms.article6.content': 'يحتفظ FashionHub بالحق في الإشراف على أي محتوى غير لائق أو مسيء أو مخالف لشروط الاستخدام الخاصة بنا وإزالته.',
    'legal.cookies.title': 'ملفات تعريف الارتباط',
    'legal.cookies.content': 'يستخدم موقعنا فقط ملفات تعريف الارتباط التقنية اللازمة لعمل المنصة (المصادقة، تفضيلات المستخدم). لا يتم استخدام ملفات تعريف الارتباط الإعلانية أو التتبع.',
    'legal.ip.title': 'الملكية الفكرية',
    'legal.ip.content': 'التصميم والشعار وجميع العناصر الرسومية لـ FashionHub محمية بحقوق النشر. أي استنساخ بدون إذن محظور.',
    'legal.contact.title': 'اتصل',
    'legal.contact.content': 'لأي أسئلة بخصوص إشعارنا القانوني أو سياسة الخصوصية الخاصة بنا، اتصل بنا على:',
    
    // Messages page
    'messages.title': 'الرسائل',
    'messages.subtitle': 'تواصل مع عملائك ومزودي الخدمات',
    'messages.loginRequired': 'تسجيل الدخول مطلوب',
    'messages.loginMessage': 'سجل الدخول للوصول إلى رسائلك',
    'messages.searchPlaceholder': 'ابحث عن محادثة...',
    'messages.noConversations': 'لا توجد محادثات',
    'messages.startConversation': 'ابدأ الدردشة مع أعضاء آخرين',
    'messages.typeMessage': 'اكتب رسالتك...',
    'messages.send': 'إرسال',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
